### ISSUE TITLE
Deprecate support for Kirby panel version < 2.2.0

### ISSUE THREAD

**Issue by distantnative** [distantnative/panel-bar#102]
Time to develop nice working version for panel 2.2.0 between v1.0 and v2.0

**Comment by jenstornell** [comment]
For new fixes and features, will that be added to both versions (development branch)? I prefer using Kirby 2.1 until 2.2 is released.

**Comment by distantnative** [comment]
I will try to bring real bugfixes do botch versions v1 and v2. Thus, there is still the `develop` branch with refers to v1 and still supports Kirby 2.1. On the `develop-v2` branch I will work on v2 which won't support Kirby 2.1 anymore. panelBar v2 won't be released before Kirby 2.2 has been released.

Some enhancement fixes probably will only make it to v2 if integrating it into v1 would be too much work. Same goes for new features, that will only make it to a v1.1 if it's little work.
