### ISSUE TITLE
Improve existing code

### ISSUE THREAD

**Issue by distantnative** [distantnative/panel-bar#109]
**PHP**  
- [x] Consistent class functions (public/protected/private)
- [x] Check namespacing
- [x] Revise naming of classes (e.g. `toolkit`) and files
- [x] Add PHP version required to docs
- [x] Better inline documentation of code / comments

**JS**  
- [x] Better connect/integrate modules
- [x] Better naming of instances, objects/classes
- [x] Check error catching (more tests if browser features present)
- [x] Better inline documentation of code / comments

**(S)CSS**  
- [x] Remove nesting
- [x] Try to minimize code by more using modular classes/elements
- [x] Use mixins for redundant code
- [x] Check browser compatibility, fallbacks for non-supported features
- [x] Better inline documentation of code / comments

**Comment by jenstornell** [comment]
Why remove nesting of SCSS?

**Comment by distantnative** [comment]
Just minimize it. At the moment it still has some long selectors like .a .b > c .d - trying to reduce that
