### ISSUE TITLE
jQuery not defined

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#11]
Uncaught ReferenceError: jQuery is not defined(anonymous function) @ (index):20

I have jquery 2.1.4 in my footer.

Maybe you need to set it inside document ready?

**Comment by distantnative** [comment]
Ah duh, sure!

**Comment by distantnative** [comment]
Does it work now with the updated code?

**Comment by jenstornell** [comment]
No I don't get it to work.

I see that the code is output directly into the HTML. Because I have my script in the footer it will probably try to run the js before jQuery gets loaded.

**Comment by distantnative** [comment]
I see. It's already included. Try:

```php
panelbar::show(true, true, false); // first is for default elements, second for css, third for js
```

and then below jquery

```php
panelbar::js();
```

Does that work?

**Comment by jenstornell** [comment]
Yes, the javascript now work.

**Comment by jenstornell** [comment]
We should probably always add this just before </body>, not in the header.

    <?php echo panelbar::show(); ?>
    </body>
    </html>

This would probably work because the bar is fixed. It will fix JS problems.

**Comment by distantnative** [comment]
Changed the docs on the dev branch to this.

**Comment by jenstornell** [comment]
I have tried it out now and it work like expected.
