### ISSUE TITLE
iFrame: close button that redirects to current opened panel page

### ISSUE THREAD

**Issue by distantnative** [distantnative/panel-bar#111]

**Comment by jenstornell** [comment]
I really like the feature but I think the icon might be a little confusing. If we think of the panel iframe overlay as a modal the close icon indicates that it closes the modal, not that it stays in the panel.

The first icon that comes to mind is to use a kind of pin icon instead:
http://fortawesome.github.io/Font-Awesome/icon/thumb-tack/

...to pin the panel to the screen.
