### ISSUE TITLE
Shortcut alt + e issues

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#113]
1. Opens up a browser menu in Chrome on Windows 10.
1. Toggle only work when bar active or on frontend. When writing in the panel shortcuts don't work anymore.
1. I get a strange thing after edit. When only pressing alt menu starting jumping from bottom to top. I have position bottom as default in my config.

**Comment by jenstornell** [comment]
If it's no way around the "shortcut in an iframe" issue, maybe it would be best to just not toggle the edit shortcut?

**Comment by distantnative** [comment]
Works fine for me in Safari. Any Javascript errors in your console when it stops working?

**Comment by jenstornell** [comment]
Do you have Chrome to test with? I can't recall having any JS errors. Can check again tomorrow.

Just to be clear. Have you tried using a shortcut key, then writing something in a field in the iframe panel, and then press the shortcode combo?

**Comment by distantnative** [comment]
I see, that (focussing something in the iframe) was what I actually missed testing (stupid me).

**Comment by distantnative** [comment]
Problem is that once again because of security protections with iframes, once the iframe is focussed the panel bar won't get the keydown events anymore. So probably removing the toggle edit button and using the shortcut just to activate it if deactivating won't work reliably.
