### ISSUE TITLE
Inconsitent naming

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#116]
The name of the panelbar / panel-bar changes depending on where we are...

### `panel-bar`

- On github
- In plugins folder

### `panelbar`

- Elements like panelbar::link();

I know it comes late and it's probably hard to make something about it?

**Comment by distantnative** [comment]
Going for `PanelBar. Not sure if I should also adapt it in code parts like
```php
<?php echo PanelBar::show() ?>
```

**Comment by jenstornell** [comment]
Maybe use the Kirby convention?

http://getkirby.com/docs/cheatsheet/dimension/fit-width-and-height

```
$dimension->fitWidthAndHeight()
```

Camelcasing starting with a lowercase for the first character?`

**It would be**

```php
<?php echo panelBar::show(); ?>
```

I just like to be consistant so we still feel it's Kirby (even if this is a plugin).

**Comment by distantnative** [comment]
True. I think then I'll adapt the name everywhere (except in the repo, that will stay `panel-bar` to panelBar.

**Comment by jenstornell** [comment]
(y) How do I do thumbs up on Github? ;)

**Comment by distantnative** [comment]
with `:+1:` :wink:

**Comment by jenstornell** [comment]
:+1:
