### ISSUE TITLE
Position left / right - Feature request

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#117]
This a big feature request. It should probably have it's own version, if developed.

![image](https://cloud.githubusercontent.com/assets/927011/10448436/2bb9416c-718d-11e5-8c14-91f945492a29.png)

### When it's needed

On my current site I have a sticky header and when doing stuff I get ajax messages on a sticky bottom. I can switch between top and bottom all the time or hide the panelbar but I have a really large screen. I have alot of space on the sides. If I could set it there I might not need to move the panelbar around very much.

### Problems

- There might be new CSS issues.
- The icon will not longer work as it switch as a toggle, top and bottom.
- Responsiveness might be a problem as well.

**Comment by distantnative** [comment]
I will think about it - for me biggest problem seems to be dropdowns

**Comment by distantnative** [comment]
Thought about it. But it seems to much work to me, too many new problems and issues, so that I won't add this anytime soon.

**Comment by jenstornell** [comment]
Totally fine!
