### ISSUE TITLE
Images - Transparancy pattern a little bit tiny

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#118]
Do this first and it will be easier to change:
https://github.com/distantnative/panel-bar/issues/115

I use a large screen and it makes the pattern a little bit small. Maybe something like this?

```
background-color: #fff;
    background-image: linear-gradient(45deg, #ddd 25%, transparent 25%, transparent 75%, #ddd 75%, #ddd), linear-gradient(45deg, #ddd 25%, transparent 25%, transparent 75%, #ddd 75%, #ddd);
    background-size: 20px 20px;
```

**Comment by distantnative** [comment]
Something seems to be wrong with that pattern... 
<img width="200" alt="screen shot 2015-10-13 at 19 17 29" src="https://cloud.githubusercontent.com/assets/3788865/10462459/1a5fcbbe-71df-11e5-9295-b792377c0791.png">

**Comment by distantnative** [comment]
Got it working with

```css
      background-color:     #fff;
      background-image:     linear-gradient(45deg, #e8e8e8 25%, transparent 25%, transparent 75%, #e8e8e8 75%, #e8e8e8), linear-gradient(45deg, #e8e8e8 25%, transparent 25%, transparent 75%, #e8e8e8 75%, #e8e8e8);
      background-size:      20px 20px;
      background-position:  0 0, 10px 10px;
```

**Comment by jenstornell** [comment]
For me, background-size 10px and 20px worked but not 15px. I guess it has to do with some calculation. Good that it works for you. Will test it tomorrow.

**Comment by jenstornell** [comment]
Is this still a problem? It works for me.

**Comment by distantnative** [comment]
Since you said size 15px
