### ISSUE TITLE
Images - Remove line between extension and filesize?

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#119]
I like that both extension and filesize is showing on hover. I'm not that sure about the line in between. I think it's a little bit distracting. I think it chould be removed.

**Comment by distantnative** [comment]
Actually, I really like that line

**Comment by jenstornell** [comment]
Ok then. I will try one more time before I give up. Which of them do you think is most readable? I think the one without the line.

![image](https://cloud.githubusercontent.com/assets/927011/10511760/df69b520-733b-11e5-84a8-6c73d00da753.png)

**Comment by distantnative** [comment]
Don't see a difference regarding to readability.

**Comment by jenstornell** [comment]
Ok then. I'm closing it.
