### ISSUE TITLE
Images - Too much space with 1 or 2 images

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#120]
This image does not need all this space. It appears with 1 or 2 images. More images are fine.

### Suggested solutions

1. Recode CSS to make some dynamic with of the element, like inline-block or flexbox. Make it feel the width by letting the images pressing the walls.
1. Make cases for the first and second image.

![image](https://cloud.githubusercontent.com/assets/927011/10448818/b54a68d2-718f-11e5-843d-71d029f13b73.png)

**Comment by distantnative** [comment]
Actually I'm already doing both. Need to investigate why for you the 1/2 image cases don't trigger.

**Comment by jenstornell** [comment]
Ahh, wait! Don't do anything!

**Comment by distantnative** [comment]
Ahh. Yes, PHP counts the files/images and applies a class for 1, 2, default or more then 12. And based on these classes some min-width and stuff is applied.

**Comment by jenstornell** [comment]
Solved then but if it's possible to do it with pure CSS I think it would be nicer but it works so it's fine.
