### ISSUE TITLE
Idea - Remove "All images" and make the element linked

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#121]
At the bottom there is "ALL IMAGES". It's a good function but it takes up space.

### Idea

1. My idea is to remove "ALL IMAGES" link at the bottom.
2. Make the element name "Images" linked to all the images.

So, when clicking "Images" we go to all the images. Else we hover to get the images for this page.

Maybe it will conflict with the behavor of mobile devices, if they click to show the dropdowns?

![image](https://cloud.githubusercontent.com/assets/927011/10449216/5f7ec288-7192-11e5-89bf-8261b56efdfa.png)

**Comment by distantnative** [comment]
Thought about it, but thinking that making the label a link would really create problems on mobile devices. So not atm.

**Comment by jenstornell** [comment]
Ok, I'm fine with it.
