### ISSUE TITLE
Header set X-Frame-Options "DENY" breaks some of panel-bar actions

### ISSUE THREAD

**Issue by rhawbert** [distantnative/panel-bar#122]
In my .htaccess, I'm using some of html5boilerplate's anti-clickjacking and the default options doesn't allow some redirects like the one on "Edit" button.

https://github.com/h5bp/html5boilerplate.com/blob/master/src/.htaccess#L190

One has to change the default value of `X-Frame-Options` header from `DENY` to `SAMEORIGIN` in order for it to work.

Lots of security implications thou... since this might not be the best setting for everyone as described on html5boilerplate's source.

**Comment by distantnative** [comment]
Probably not much that I can change from my side. But I will try if I could detect this and then simply let the links work as links instead of trying to load them in the iframe.

**Comment by distantnative** [comment]
Leaving this here for me: https://blog.whitehatsec.com/x-frame-options-xfo-detection-from-javascript/

**Comment by jenstornell** [comment]
Good solution for that problem. Use direct links to the panel if iframe is blocked. Or what do you think about it @rhawbert ?

**Comment by rhawbert** [comment]
Hi @jenstornell, I'm not a security expert was just trying to follow some good practices...

It'd be ideal, in the user experience point of view, if @distantnative managed to make it work in every case/configuration/server... but I do agree that there're too many variables (servers, hosting companies, etc.).

I believe a progressive enhancement approach would be a better fit thou... I mean, make it work without the bells and whistles.. then improve it to the ones that are technically able to get the improvements.

**Comment by jenstornell** [comment]
If there are so many variables to consider an easy way would be a config value.

panelbar-iframe: true / false

**Comment by distantnative** [comment]
> It'd be ideal, in the user experience point of view, if @distantnative managed to make it work in every case/configuration/server... 

Totally agree. But since the `X-Frame-Options` are prohibiting exactly what I'm trying to do, it won't be possible if not set (at least) to `SAMEORIGIN`

**Comment by jenstornell** [comment]
Ok, sounds good to me.

**Comment by distantnative** [comment]
Added the progressive enhancement workaround to the develop branch.
