### ISSUE TITLE
Don't show images if not allowed in the panel?

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#123]
If this feature already exists, just close this issue.

Dont' show the image element if it's not allowed on the page set by the blueprint.

**Comment by distantnative** [comment]
Yea, same with a lot of other things (add, edit, permissions).
Getting the feeling that I will need to actually include the panel object itself.

**Comment by jenstornell** [comment]
You could parse the blueprint but I read your other issue and it would be many benefits of including it. The only downside I see would be if it slows down the site, but I think the panel is really fast.

I would not recommend it if this was WordPress, but it's Kirby.

**Comment by distantnative** [comment]
> The only downside I see would be if it slows down the site, but I think the panel is really fast. I would not recommend it if this was WordPress, but it's Kirby. Include the panel object and see if it's still fast.

I just included it and locally, the loadtime element went from `0.05` to `0.08` or sometimes `0.10`.

**Comment by distantnative** [comment]
Added to `develop-v2` branch.

**Comment by jenstornell** [comment]
Is that good or bad? If it's too slow...

- Cache it somehow
- Load everything with ajax
- Use it now and walk away from it later on using own functions.
