### ISSUE TITLE
Directly work with panel object

### ISSUE THREAD

**Issue by distantnative** [distantnative/panel-bar#124]
Would be useful for:

- only show panel bar if panel exists
- panel version
- urls
- show elements based on blueprint settings/permissions

**Comment by jenstornell** [comment]
Should we still have the issue about allowed images open? Maybe all that stuff should be in a version? The "Panel object" version?

**Comment by distantnative** [comment]
Leave it open, smaller issues are always nicer to finish. And yea, that's pretty much what I will try to make the v0.8

**Comment by distantnative** [comment]
Okay, I actually had a closer look at this. And since a lot will change in the foundation of the panel with the upcoming 2.2.0, it makes little sense to integrate it now with constantly checking and handling whether PanelBar has to work with a panel version < or > as 2.2.0. They are simply that different in parts.

I already decided that I want to make PanelBar require a panel with 2.2.0 at some point. I still would like to release a stable and complete version of PanelBar that works with 2.1.1 - that will be PanelBar v1.0. So all the integration work, I will delay for a 2.0 version.

**Comment by jenstornell** [comment]
Sounds good.

**Comment by distantnative** [comment]
Added to `develop-v2` branch.
