### ISSUE TITLE
Element: Page weight

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#128]
Here I come with another big idea. I don't know if this is a good feature or just a good plugin for panelbar. Your choice.
### Page weight

Look at the last item at the right. It shows the page weight.

![image](https://cloud.githubusercontent.com/assets/927011/10534981/c6c92278-73de-11e5-9b60-d3d992ce9fa0.png)
### What is page weight?

**I think it's a sum of:**
- HTML size
- JS size
- CSS size
- Images size
### On hover

On hover it could come up some infobox. It will give more details about what takes up space, the images, the JS or CSS, maybe HTML. I made no screenshot of that.
### Ajax required

We don't want it to calculate the panel so Ajax is needed to get a not logged in version to measure. Another benefit of using Ajax would be that it's not a load blocker.

Core feature or possible plugin for someone to make?

**Comment by distantnative** [comment]
Sounds great. I'd also like to include that as a standard element, will put it on the list for 2.0-alpha2 (alpha1 will be for the panel integration and panel 2.2.0 requirement, alpha2 for new features like this). Might also bring it back to a possible v1.1, but I decided that I want to have kind of a feature stop for v1.0 and only do enhancements to the current code, cleaning and bug fixing to get a first complete and stable v1.0.

**Comment by jenstornell** [comment]
Sounds good. Stable before adding new features on top.

**Comment by distantnative** [comment]
http://blog.trasatti.it/2012/12/measuring-the-speed-of-resource-loading-with-javascript-and-html5.html

**Comment by jenstornell** [comment]
The link calculates speed and number of things but not the size of the things. For that the only way is probably PHP / Ajax.

**Comment by distantnative** [comment]
Just wanted to leave the article about the performance interface somewhere.
