### ISSUE TITLE
Toggle-switch disapears

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#13]
The toggle-switch is sometimes black and sometimes white. Both colors are use by my design. The white should always work if the issue with toggle-switch placement would be solved.

The black appear when the menu is hidden. It has no color to fall back on. When scrolling it disapears on my site in some places.

A solution would be to somehow set the plus sign to white (now its hollow). Then there would be a white plus with black background. It will work on black, white or any other color.

**Comment by distantnative** [comment]
Will try to see what can be done with this icon font

**Comment by jenstornell** [comment]
Maybe use :before in CSS on that element and use circle as a background?

http://fortawesome.github.io/Font-Awesome/icon/circle/

**Comment by distantnative** [comment]
Sadly I can't get it below the actual icon

**Comment by jenstornell** [comment]
You might need to edit it a little bit but this work:

    .fa-plus-circle:before {
        content: "\f055";
        z-index: 100;
       position: relative;
    }
    .fa-plus-circle:after {
        content: "\f111";
        position: absolute;
        top: 0;
        left: 0;
        color: #fff;
        z-index: 50;
    }

**Comment by distantnative** [comment]
Solved it a bit differently
