### ISSUE TITLE
Solution - Controlling gallery width with pure CSS

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#130]
I have done some testing to see if it's possible to make the gallery container "feel" how many images there are and adapt to that and I succeeded.

### Autoadapt 3 images

![image](https://cloud.githubusercontent.com/assets/927011/10535244/63a9ce24-73e1-11e5-83ed-9abb4ca18c03.png)

### Autoadapt 4 images

We don't have 4 images in a row. Just tried out the concept.

![image](https://cloud.githubusercontent.com/assets/927011/10535250/70c83bcc-73e1-11e5-954f-e12b9c61452b.png)

### Solution explained

Three dots means that keep what's inside, just add.

```
.panelbar-fileviewer__grid--default {
    ...
    white-space: nowrap;
}

.panelbar-fileviewer__grid--default .panelbar-fileviewer__item {
    width: 150px;
    display: inline-block;
}
```

### Breaking at 3 images

We want to break with 3 images in a row and that is done with a nth-child(3) or what it would be.

### Benefits

- What can be done with just CSS should probably be done with just pure CSS.
- Less PHP code and not so much more CSS code.
- Better separation between PHP and CSS.
- Easier to search for CSS errors in the DOM. No more fiddling with classes.

**Comment by distantnative** [comment]
But if we have `white-space: nowrap;`, what's the CSS code for `:nth-child(3n+3)` to break after it (also sometimes we have 4 or even 5, but that case could still be handled as it is now)?

**Comment by jenstornell** [comment]
This usually work. Add it to the element that needs a break after it.

```
:after {
    content: '';
    display: table;
    clear: both;
}
```

**Comment by distantnative** [comment]
Sadly, that doesn't work.

**Comment by jenstornell** [comment]
Ahh, yes. It's not float, forgot that. Try this:

Insert a linebreak (`<br>`) with content:

```
:after {
    content:"\a"
}
```

http://stackoverflow.com/questions/10933837/line-break-like-br-using-only-css

**Comment by distantnative** [comment]
Yea, tried that, but it also doesn't work. This is driving me really nuts.

We have a wrapper with `white-space: nowrap`and elements as `inline-block` -> I only get one endless row.
With `white-space: normal` I only get 1 element per row without specifying a width for the parent.

And using float on the elements also just create 1 element per row without a parent width.

**Comment by jenstornell** [comment]
```
.selector:after {
    content:"\a";
    white-space: pre;
}
```

**Comment by distantnative** [comment]
<img width="646" alt="screen shot 2015-10-16 at 13 50 20" src="https://cloud.githubusercontent.com/assets/3788865/10540917/dc5db472-740c-11e5-97c3-23fce05e2280.png">

:cry:

**Comment by jenstornell** [comment]
Maybe create a "Problem" branch so I can look into it?

**Comment by distantnative** [comment]
It's now on the develop branch (this one doesn't need to be always functional, so it's ok that it's broken right now, but so you can look at it).

**Comment by jenstornell** [comment]
I get the same result as you. It probably depends on

```
.panelbar-fileviewer__preview
```

There is some stuff going on inside that thing. Maybe this enhancenment can be pushed to version 2 or so.

**Comment by distantnative** [comment]
I might just use `flex` instead of ìnline-block`?

**Comment by jenstornell** [comment]
Where did you comment go?

>I might just use flex instead of ìnline-block`?

Flexbox is future proof but might not work with all older browser like IE8. However, I don't think any Kirby developers are using IE8 when developing with Kirby. If it works, I say go for it!

**Comment by distantnative** [comment]
I deleted it since I think `flex` actually has the same problem (since the markup just has `__item`s adn isn't divided into rows or so.

**Comment by jenstornell** [comment]
I have tried flex-wrap.

https://css-tricks.com/almanac/properties/f/flex-wrap/

**Comment by distantnative** [comment]
Atm I think best bet would be to find a way with floating elements that expands the parent's width. Cause then I could say e.g. every 4th element `clear: left`.

**Comment by distantnative** [comment]
A working solution with `flex-wrap`?
I just got a 1-item-per-row result again. :/

**Comment by distantnative** [comment]
Yea, giving up. For the moment, PHP will add a class, but I'll streamline it a bit.

**Comment by jenstornell** [comment]
**I just figured it out:**

http://jsfiddle.net/Lt0ea0rt/2/

It's really working! Now it's just for you to figure out how to implement it to the panelbar.

**Comment by distantnative** [comment]
Not really. Cause `max-width`doesn't work in our case here, so that I need PHP classes again to tell what width to set the whole grid :(

**Comment by distantnative** [comment]
Will open an issue to tackle this again in 2.0
