### ISSUE TITLE
Image space are different

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#132]
The space in between the images are not the same as above / below them. It's seen clear on hover.

![image](https://cloud.githubusercontent.com/assets/927011/10535452/5a4c8aa4-73e3-11e5-9eba-d209fc24e150.png)

**Comment by distantnative** [comment]
Should be fixed.

**Comment by jenstornell** [comment]
Yes but now there is a padding to the left of the box that is not equal to the right.

![image](https://cloud.githubusercontent.com/assets/927011/10599988/8818856a-7707-11e5-9db8-2a21f1bde7ec.png)
