### ISSUE TITLE
Filelist - Hide preview if there are no images

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#134]
When adding file that are not images it still shows space for an image preview. In this case that space has no meaning.

That is the downside of having image preview in the filelist or having the images to the left. If the preview was on the right it would not be visible but then if the image preview was on the right the feeling might get hurt.

Some idea? Hide preview if no file is an image?

![image](https://cloud.githubusercontent.com/assets/927011/10540427/1cbb290a-7408-11e5-9207-77f1dbe85975.png)

**Comment by distantnative** [comment]
I'll try #135, so that should solve this issue as well.

**Comment by jenstornell** [comment]
Agree, fine with me!
