### ISSUE TITLE
Filelist - Icon for not images

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#135]
Now there is just a white space if a file is not an image in the filelist. I think it would be better with an icon or something set as a background or image.

**Suggestions of icon**

- File icon (White paper)
- Question mark
- Extension type (would be a huge feature as there are hundreds of file extensions. Probably not possible)

**Comment by jenstornell** [comment]
About the suggestions. I've been thinking and it could be nice to have like a default filelist icon for unknown filetypes, as a start.

Then if there is an icon for example PDF-files in font-awesome, then why not use it? Most of the people probably add these common files anyway (except for images):

- pdf
- doc
- txt
- docx
- md
- json
- zip

I'd say, support max 10-20, not more than that, to not bloat the code.

**Comment by distantnative** [comment]
Added it to the dev branch with the following logic:

```php
switch ($file->type()) {
      case 'archive':
        return 'file-archive-o';
        break;
      case 'code':
        return 'file-archive-o';
        break;
      case 'audio':
        return 'volume-up';
        break;
      case 'video':
        return 'film';
        break;
      case 'document':
        switch ($file->extension()) {
          case 'pdf':
            return 'file-pdf-o';
            break;
          case 'doc':
          case 'docx':
            return 'file-word-o';
            break;
          case 'xls':
          case 'xlsx':
            return 'file-excel-o';
            break;
          case 'ppt':
          case 'pptx':
            return 'file-powerpoint-o';
            break;
          default:
            return 'file-text-o';
            break;
        }
        break;

      default:
        return 'file-o';
        break;
    }
```

LEt me know if you have more suggestions for file format icons.

**Comment by jenstornell** [comment]
archive, code, audio, video. They are not extensions right? They are sections like document? In that case, go for it. Code icon might not be perfect but everything else looks good at first sight.

http://fortawesome.github.io/Font-Awesome/icon/code/ is better?

**Comment by distantnative** [comment]
Ah indeed better suggestion. Will change it. And archive, code etc. are detected file types by kirby. Saves the work to list all kinds of extensions.

**Comment by jenstornell** [comment]
Looks nice to me. Maybe a little messy with all filetypes just thrown in but I think it will look good on a real environment where you often have the same kind of files.

Is it maybe better to sort them by extension? and second sorting by alphabetically?

**Comment by distantnative** [comment]
True. Will open an extra issue for that.
