### ISSUE TITLE
Fileviewer: control responsive width via pure CSS

### ISSUE THREAD

**Issue by distantnative** [distantnative/panel-bar#136]
Might need to just rewrite the fileviewer markup and CSS to get a clean slate.

**Comment by jenstornell** [comment]
A new solution. A combination with `display: inline-block;` and `float: left;` and nth-child.

No max-with this time.

http://jsfiddle.net/zcon61jL/1/

Maybe you need a clean slate to make it easier to implement.

**Comment by distantnative** [comment]
No sadly still doesn't work. Somehow the `position: absolute` on the grid also forces it to have the most minimum width it can.

**Comment by jenstornell** [comment]
I guess it has to do with your code. I use position absolute here now, as a wrapper arount it:

http://jsfiddle.net/zcon61jL/3/

**Comment by distantnative** [comment]
True. :D

**Comment by distantnative** [comment]
Ok, I just have put a few more hours of thought into this and I'm afraid there is no nice solution for this because of two issues that prevent solving the other one:

1. The main panelBar container is positioned fixed, the dropdown menus are positioned absolute to their relative `li` parent inside the fixed main `div`. Only this way I can make them appear center below the corresponding menu entry.
2. With this inheritance I just can't get any children within the dropdown (that also have to be responsive) push the width of the absolute positioned dropdown container. No way.

I can solve the second by using `position: fixed` for the dropdown menus. But then again I can't find any way to make the dropdown appear in center below its menu item.
