### ISSUE TITLE
Replace Files by Filelist, remove Imagelist

### ISSUE THREAD

**Issue by distantnative** [distantnative/panel-bar#138]
Would like to hear your opinion on this idea, @jenstornell :

Basically getting rid of Filelist and Imagelist element.
Images element stays the fileviewer grid with large preview.
Files becomes the former Filelist list of files.

Thoughts?

**Comment by jenstornell** [comment]
Yes! That was what I thought before I changed `files` to `filelist`. I see no reason for files to be a gallery.

The other way around may still be useful. I mean to be able to have images as a list, especially if having many images, or focus will be on filesize. Then it's a better pick.

I would say, remove `files`, and keep only `filelist` but I'm not sure about removing `imagelist.

**Comment by distantnative** [comment]
Yea, just thought the same. :+1:
