### ISSUE TITLE
More kirby panel style

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#14]
More like the panel. If you disagree you can just close it.

- Solid lines
- Change edit icon

**Comment by distantnative** [comment]
Edit icon is already on the dev branch.
Solid lines could work - panel uses some linear-gradient I believe as well on them.
Still contemplating on the white dropdown or keeping the current black one.

**Comment by jenstornell** [comment]
I tried it out in Photoshop. The white rocks! My vote is on using that style. It looks good on black as well as white (because of the shadow).

**Comment by distantnative** [comment]
I added the dropdown style. Anything else that you can spot?
