### ISSUE TITLE
JS component: Global page HTML output string

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#144]
I think it can be good with a global HTML string of the HTML output from Ajax. I will explain what I mean.
### Example

Let's say you implement "Page weight" as an element. It uses Ajax to fetch the page HTML.

Then you or someone add another element, for example to count broken links on the page. Then Ajax is needed to fetch the page HTML.

This would in normal case require two Ajax requests where both fetching the same thing, the page HTML.

Therefor I think it could be nice to have a kind of global string of the HTML output from Ajax. I don't know how.

**Comment by distantnative** [comment]
Doesn't really feel like a good way to implement it. I think there are better tools to measure page performance than the panelBar could ever offer.

**Comment by jenstornell** [comment]
The issue is not about measuring the page performance. It's about having the page only fetched onces with ajax. Else 10 elements could possibly try to get the page with ajax and that would not be good performance. So the issue is about a way to get the html from the panel-bar instead of need to make the ajax call on an element level.

Do you know what I mean?
