### ISSUE TITLE
Element: SEO

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#145]
Ajax fetching HTML content to display SEO (Search Engine Optimization) stuff.

**An infobox with the following**

Like an SEO checklist. Here is just a few things:
- Title (+ character count)
- Meta description (+ character count)
- Meta robots (page blocked or not)
- h1 (exists or missing + character count)
- Wordcount

**Comment by distantnative** [comment]
I probably won't have time for these issues anytime soon. But if you feel like starting it as a custom element, I'd be more than willing to include it eventually.

**Comment by jenstornell** [comment]
I don't know if I will do that.

I still have thoughts of an SEO thing, but right now I feel that it should be some kind of SEO archive list of all the pages of one level (with pagination). That list should be in the panel, as a panel admin page (if it's developed in the future).

A little bit like Yoast SEO for WordPress but much much better of course. :)

**Comment by jenstornell** [comment]
You say you don't have time of "these issues"? Does that mean all issues or just the larger plugin kind of issues?

I hope you still have time to fix minor issues like bugs and make it work with future Kirby version. Just maintain will mean that the plugin stays alive.

**Comment by distantnative** [comment]
"These issue" referred to a vague number of feature issues - I haven't decided yet what I can do and what I cannot. I def still wanna do bugfixes. Which also implies that I still hope to get that 2.0 version done sooner or later.

**Comment by distantnative** [comment]
Not really sooner, but I guess I have something that you could call a 2.0.0-alpha on the develop branch. Still a lot to do to improve code quality and readability as well as important bugfixes (mainly for the files/images element), but I really like where the code has evolved. Especially in terms how you will be able too create Element plugins and register them through an own panelBar registry.

**Comment by distantnative** [comment]
If you are still interested in a SEO element, I would appreciate some "rules" what the element should check the page for. Cause I have no real idea of SEO...

**Comment by jenstornell** [comment]
The most important things are in the descriptions but other than that there are almost endless of possibilities. Image Alt-tags is an easy to forget SEO measurement that I forgot to write. Every image should have an alt-tag that is not empty.

Maybe I'll make an element for it in the future.

**Comment by distantnative** [comment]
Yea, I guess it really doesn't make sense for me to create and maintain such an element, not knowing enough about SEO myself.

Maybe rather create an element e.g. for https://developers.google.com/speed/docs/insights/v2/first-app
Or is there any API specific for SEO?

**Comment by jenstornell** [comment]
I agree. It's better to let panel-bar only handle Kirby specific things. Leave the rest to the browser. Close this issue if you want.

**Comment by distantnative** [comment]
I know, it's not SEO, but it is likely to be the closest what I will ever include in the plugin itself: https://forum.getkirby.com/t/panelbar-2-like-an-old-friend-you-havent-seen-in-years/7061/8?u=distantnative

But if you come up with an element plugin, let me know :)
