### ISSUE TITLE
Idea - Plugin or core - Kirby version?

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#146]
An element with Kirby information, an infobox with:

- Kirby version (check if latest?)
- Panel version (check if latest?)
- Toolkit version (check if latest?)
- Maybe other stuff

**Comment by distantnative** [comment]
Just pushed it to the develop branch- With this you can deactivate the api check with github (which takes quite some time sadly):
```
c::set('panelbar.system.api', false)
```

**Comment by jenstornell** [comment]
I did not get it to work. I used development branch:

Is this wrong?

```php
c::set('panelbar.elements', array(
  'panel', 
  'edit',
  'system'
));
```

If system is added the bar will disapear (and never appear even on shortcut).

**Comment by distantnative** [comment]
Argh, sorry I worked quite a bit on re-structuring last night, namespaces and so on. I think that I broke quite a few things during that, hope to have them fixed soon.
