### ISSUE TITLE
Element: Security check

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#147]
An element as a checklist for some security issues:
- Current page txt file permission?
- Current user password strength?
- Latest versions of Kirby installed?
- I don't know what to put in there.

(I brainstormed yesterday so I spam a little bit all the ideas.)

**Comment by jenstornell** [comment]
Just wanted to add... In this list, the only thing that might be relevant from it in real life is probably:

- Latest versions of Kirby installed? (green / red, checkbox?)

There are more things about security but I'm not a pro of the security part.

**Comment by distantnative** [comment]
I agree, the versions are probably the most important part. They are included in the `system`element.
