### ISSUE TITLE
Idea - Universal panel

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#148]
This panelbar is for Kirby but only the elements are bound to Kirby. I think this could be an universal bar.

Let's say it would be for WordPress. It would not be much to change to make it work. The elements and maybe hook it to wp_footer.

Maybe it could work on Drupal and Joomla as well. Just an idea.

**Comment by distantnative** [comment]
Interesting idea, but actually it needed some changes, not using the toolkit... And I feel it makes more sense for the moment to focus on Kirby and not try to create something very broad that isn't really committed to be good for any particular platform. Just all over the place. Maybe something to think about for a v3 - but that's too far ahead for now.
