### ISSUE TITLE
Toggle-switch behavior

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#15]
When scolling down a bit on the page and click hide the menu hides nicely.

When at the top and hide it, it creates a gap of 50px. That is not so nice.

### Possible solution ###

I write some pretended code and see if you understand me.

    if( click on hide && window.top > 50px ) hide()
    else remove space from body, then hide

    if( click on show && window.top > 50px ) show()
    else add the space to body, then show

When on top, it snaps to the top and push the page down. When not on top it does not need to do that.

Ask me if I'm not clear.

**Comment by distantnative** [comment]
I tired this, but it causes problems:

What if you start hidden on top (no space), toggle it (space), scroll down, toggle it (still space) and then scroll up. Then you have this gap again.
If you always remove the space, the page starts to jump a little. 

Other option would be to completely remove the gap and have the panel bar over potential header content. Or to work with a scroll listener, but that seems to be nasty.

**Comment by jenstornell** [comment]
Yes. I think it's ok to never add a gap.

## Bottom solves it
Because the panel bar can set on bottom it should not be a big issue.

## Flip switch makes it a breeze
If you add the "Flip switch" (see another issue) it would be even more natural.

## Bonus - Fix bugs naturally
It would also solve future problems with the "hackish" margin-top on the body element. I mean sometimes there are already some css added to the body.

**Comment by distantnative** [comment]
Yea, I agree with you. Let's kick it out for now.
I was already unhappy, thinking about someone who actually uses body.padding-top for their styling.
