### ISSUE TITLE
Edit panel, close without save and then open loses data

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#151]
When edit a page without saving and just closing the window the iframe closes without reload. When editing again the iframe is not just shown again, but reloaded again. That makes my unsaved data disapear.

Maybe store a value in localstorage to check if we just left the edit panel without save. It would also make the edit faster when closed with unsaved data.

**Comment by distantnative** [comment]
The iFrame is unloaded on close for cleaner opening of other links after returning.
I could remove that. But then again, the panel should cache unsaved changes itself?
<img width="734" alt="screen shot 2015-10-20 at 10 16 26" src="https://cloud.githubusercontent.com/assets/3788865/10601703/a6a54688-7713-11e5-81d3-ef653c0c141e.png">

**Comment by jenstornell** [comment]
It did not save the data for me but maybe it takes a while before it starts caching the data?

I don't know exactly how it works with the iframe. You can close it if this idea is not good. I can't really deside.

**Comment by distantnative** [comment]
Works for me flawless - at least with the panel 2.2 version. Go in edit mode, just add one letter to the title, immediately click return to page. When I enter edit mode again it's already cached. So even after little time. Maybe it works better with panel 2.2.
