### ISSUE TITLE
Idea - Item counter

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#153]
On hover I can see that I have 4 images. When not on hover I don't know if I have 1 or 100 images.

**Maybe a counter would be a good thing. There are as I see it two possible solutions:**

1. Make it like a small round thing with a number in it, just like Facebook when having messages.
1. Like this: **Images (12)**

It would be good on Images, Imagelist and Files.

**Comment by distantnative** [comment]
Added to the develop branch:
<img width="546" alt="screen shot 2016-01-17 at 18 42 34" src="https://cloud.githubusercontent.com/assets/3788865/12378805/2b3f462e-bd4a-11e5-903d-60f4c1536632.png">

**Comment by jenstornell** [comment]
I just want to say, it looks really good!
