### ISSUE TITLE
Pattern: Box styles

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#154]
Now there are box and links where box is ment to have anything in it. We then need to add some custom CSS to use it.

I think a nice thing would be to apply some default styles in there. Possible default styles:

**Value pairs**

Might be good for checklists, like SEO checklist or security checklist.

```
Headline1 - Information
Headline2 - Information
            More information about headline 2
Headline2 - Information
```

**Sections**

Might be good for larger more informational purposes.

```
Headline1
Information

Headline2
Information
More information about headline 2

Headline2
Information
```

Maybe this can be new elements inherit from infobox.

**Comment by distantnative** [comment]
Added to the `develop` branch, documentation will follow. Best shown in the `system` element: https://github.com/distantnative/panel-bar/blob/develop/elements/system/system.php#L24-L60

Options to include in the `box` key array to use the template:
- `null`: horizontal line
- `string`: text that will be run through `kirbytext()`
- `key => value`: presented as `Key: Value`
- `key => array`: like key value, but with the array keys `label`, `url`, `external`
