### ISSUE TITLE
Pattern: Modal element

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#158]
Maybe there is much information in an element. Sometimes it might be relevant with a modal (popup), for example to tell about security, SEO or Kirby versions. The idea is to still trigger it from the panelbar but it appear as a lightbox / modal / popup / window instead.

Maybe everything can still fit the hover menus, but I just want to drop the idea before I forget it.

**Comment by distantnative** [comment]
Only 1.5 years later and your request has been just added as component/feature on the `develop` branch 🤣
