### ISSUE TITLE
Idea - Iframe element

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#159]
Think of a fullscreen page. A table with broken links, thier error codes, information and so on. That kind of information would not fit into the panelbar of today, I mean a giant table.

I think it could be cool to use the iframe that now contains the panel, and keep the admin panelbar on top. Maybe change the iframe element to a div in that case.

I don't know if Bastian want to implement a way to add these kinds of pages to the panel directly. If that is the case, this feature might needed at all. In that case panelbar could just link to these pages.

**Comment by distantnative** [comment]
I see your point, but I just hope that it will eventually gets included into the panel directly. I think it's too big of a thing for the panelBar. panelBar shouldn't be an alternative to the panel for some things.

**Comment by jenstornell** [comment]
I agree!

Another thought, if the standpoint is that the panelbar should not be an alternative to the panel, then the visible / invisible feature is not in line with that philosophy.

Every other feature is just linked to the panel, but visible / invisible is taking over the panel functions.

I don't like the visible / invisible feature in the first place so I don't use it.
