### ISSUE TITLE
Mobile - Don't hide custom dropdown text

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#16]
In the edit choice it hides the text when on a mobile device. It does not do that on my custom dropdown menu. I think it should?

**Sidenote:** Can't I set a label on an issue on github myself? I can't find where if so.

**Comment by distantnative** [comment]
Did this cause I found it better to still see the language codes instead of the flag. But I get, that for other dropdowns this might not be the case.

Sidenote: I'm afraid not.

**Comment by distantnative** [comment]
I will add an option to the element helpers, to set whether label or icon should be responsively hidden. Any good name for the option?

**Comment by distantnative** [comment]
Idea would be `mobile` and you set what should be left in mobile view... good?

**Comment by jenstornell** [comment]
You mean like?

    'mobile' => 'text'

or

    'mobile' => 'icon'

?

If above is what you mean, I think it's ok.

But should it be used to set alternative texts instead of just "text"?

I think it should fallback on the icon (as default), if an icon is used.

**Comment by distantnative** [comment]
Setting alternative texts will be left for a later version (I'll open a new issue for that)
