### ISSUE TITLE
Date-based pages vs. visibility toggle

### ISSUE THREAD

**Issue by rhawbert** [distantnative/panel-bar#163]
All my child folders are date based, example: ```txt 20151130-some-folder-name```.

When a page is invisible, the visibility toggle shows a dropdown as a shortcut to let the user choose where to "publish" after changing it to visible.

Is there any way to avoid (or hide) this dropdown? 

All my subpages are created using kirby's panel "builder" feature... Since the sorting is date-based the dropdown doesn't apply.

PS.: Same for the Add button... I'd like to not offer an option to add child pages... adding sibling would be the default option...  also no need for a dropdown here (in my use case).

**Comment by distantnative** [comment]
I see the point with date sorted pages - will adapt this in the upcoming v2 which requires Kirby 2.2 (and the new panel deals quite differently with the visibility toggle anyways).

About the Add button: I think for most, child and sibling is quite useful. However, you could just replace the standard add button by your default one:

```php
$elements = array(
  'add' => panelBar::link(array(
      'id'     => 'add',
      'icon'   => 'plus',
      'label'  => 'Add',
      'url'    => site()->url() . '/panel/#/pages/add/' . $page->parent()->id();
    )),
  …
);

echo panelBar::show(array('elements' => $elements));
```

**Comment by rhawbert** [comment]
Thanks Nico

**Comment by jenstornell** [comment]
Solved? Close?
