### ISSUE TITLE
Element: "Live preview" - In the making

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#164]
I'm making a "live preview", just wanted you to know. It's an independent Kirby plugin so it does not require the panel-bar. However it's made so it can easily be added as an element to the panel-bar as well.

It's not so much of a "live" preview. More like a preview. The update is done manually.

I can give you a hint when a minefield version is done.

**Comment by jenstornell** [comment]
Are you planning to use ALT + S? I'm having a shortcut on my preview. Right now I use ALT + P but I discovered that panel-bar uses it for the panel.

I think I can use ALT + S as in "Splitscreen" or are you planning to use it in the panel-bar?

**Comment by distantnative** [comment]
No plans to use alt + s

**Comment by jenstornell** [comment]
Here is a first draft a screenshot of the preview.

- "Full panel" and "Full page" expands their part to full width.
- "Refresh this" reloads the page in the iframe. If clicked on another page that is refreshed.
- "Refresh loaded" reloads the page that matches the panel page that was first loaded.
- "X" close the splitscreen.
- ALT + S will start the splitscreen. Shortcut cannot be used to close it because of the shortcut iframe problem.

What do you think? Click the screenshot to enlarge.

![splitscreen](https://cloud.githubusercontent.com/assets/927011/10845223/5c6a52ac-7f06-11e5-8347-664bfe9b0bcc.png)

**Comment by jenstornell** [comment]
Hi Nico!

I have not seen you in a while here. I have just released a first version of my Splitview plugin for Kirby.

https://github.com/jenstornell/splitview

It would be awesome if you would like to test it and flood my repository with issues and pull requests. :)

**Comment by distantnative** [comment]
Hey Jens, I just moved to a new flat this week. I will try to test it next week! :+1:

**Comment by jenstornell** [comment]
Ahh, I see. I have a ticket for the panelBar now as well:

https://github.com/jenstornell/splitview/issues/13

**Comment by jenstornell** [comment]
To not clutter up your issue list i write here...

I can see you have not updated PanelBar in over a month. What's the reason? Client work, Kirby work? I just hope that it was not me that break you down with all my issues.

**Comment by distantnative** [comment]
Not even client or Kirby work, but non-development work and a lot of stress in general. I hope that I'll find some more time again in January. 

And no worries, you issues have been super helpful, I'd wish I could work sooner on a bunch of them.
