### ISSUE TITLE
PJAX / AJAX

### ISSUE THREAD

**Issue by ghost** [distantnative/panel-bar#165]
Hi man,

Super awesome work on the panel-bar !!
I load my pages with pjax on my site?
I have to do a hard refresh of the page for the links in panel-bar to update.
Is there a way you think to hook it all up so that it can work with ajax powered sites ?

**Comment by distantnative** [comment]
Hi man, sorry for the late reply.

I have actually never worked with pjax but let's try to solve this:
I would assume that pjax loads the content of the page via ajax and replaces the current div content with this new one, right? So is pjax focussing on reloading a specific div or whole document?

**Comment by distantnative** [comment]
Please try again with version 2.0.0 – a beta will be released hopefully within the next weeks (current status on develop branch).
