### ISSUE TITLE
JS as plugin in a scope?

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#166]
http://toddmotto.com/everything-you-wanted-to-know-about-javascript-scope/

It seems like you prefix every javascript function. You can create like plugin wrapper instead. I use it all the time now. Everything I do is a plugin. No collisions with other js stuff.

```js
var Module = (function () {
  var myModule = {};
  var privateMethod = function () {

  };
  myModule.publicMethod = function () {

  };
  myModule.anotherPublicMethod = function () {

  };
  return myModule; // returns the Object with public methods
})();

// usage
Module.publicMethod();
```

**Comment by distantnative** [comment]
:+1:

**Comment by distantnative** [comment]
Actually just managed to implement it on the develop-v2 branch. Made the files a bit messier (hope some future clean-ups will help with that) but I loved the idea to have it under the one panelBar namespace... so there is panelBar, panelBar.state, panelBar.iframe etc. now

**Comment by jenstornell** [comment]
It can be messier at first but in the long run I think it will make things easier. In this case I agree that a namespace is needed because it prevents collisions with other js stuff.

I noticed that smaller functions lasts longer, make it more readable and prevent the need for rewriting code.
