### ISSUE TITLE
Offer additional way for custom elements. designated plugins folder

### ISSUE THREAD

**Issue by distantnative** [distantnative/panel-bar#169]

**Comment by distantnative** [comment]
Started preparations: https://github.com/distantnative/panel-bar/commit/565dce1e3dcc5de62b5f2db2411c39698b530f1a

Element plugins should go into the `plugins` folder and be either a single PHP file in `plugins` or bundled in their own folder. If a subfolder is used, subfolder and the main PHP file for the element have to have the same name.

A plugin file looks basically similar to this:

```php
<?php
namespace panelBar\Plugins;

class GreatPlugin extends panelBar\Elements\Base {

  public function logout() {
    // return output
    return …
  }

}
```

It has to use the namespace `panelBar\Plugins`.

**Comment by distantnative** [comment]
It's actually ready for plugins, just needs a ton more documentation...

**Comment by jenstornell** [comment]
I just tried this and got:

Fatal error: Class 'panelBar\Plugins\panelBar\Elements\Base' not found in C:\wamp\www\kirby2.2\site\plugins\splitview-panel-bar\splitview-panel-bar.php on line 4

**Comment by jenstornell** [comment]
Maybe you can build a small example plugin? If so I have a real case for it. I need a really small plugin for Splitview.

- A button with an icon and a name (I can change it later)
- The button should just be a simple link
- The url in the link should look like this:

`[root_url]/splitview/?page_slug=[encoded_current_page_slug]`

**It will result in something like this:**

`http://example.com/splitview/?page_slug=projects%2Fproject-b`

That's it! Really simple.

**Comment by distantnative** [comment]
Will try to include an example plugin or try to provide the docs as soon as I'm done with re-structuring and so on. Sorry about that, but things change and break a lot during this time. But I still think it eventually helps the project to become more modular, easier to maintain and extend.

**Comment by distantnative** [comment]
Just built your example, @jenstornell. 

`plugins/splitview.php`:
```php
<?php

namespace panelBar\Elements;

use panelBar\Pattern;

class Splitview extends \panelBar\Element {

  //====================================
  //   HTML output
  //====================================

  public function html() {
    return pattern::link(array(
      'id'      => $this->getElementName(),
      'label'   => 'Splitview',
      'icon'    => 'columns',
      'url'     => $this->site->url() . '/splitview/?page_slug=' . urlencode($this->page->uri()),
      'compact' => true,
    ));
  }

}
```

**Comment by jenstornell** [comment]
It looks good but I don't get it to work. I have this code in my footer.php.

```php
<?php echo panelBar::show(array('elements' => array('edit', 'splitview') ) ); ?>
```

**Error message**

```
Fatal error: Cannot redeclare class panelBar\Elements\Splitview in C:\wamp\www\kirby2.2\site\plugins\panel-bar\plugins\splitview.php on line 23
```

I feel that I have a little bit hard to keep up with how things work.

**Comment by jenstornell** [comment]
I guess it will be better for me to maintain the Splitview plugin in case I change how the Splitview plugin work? I created a repository for it and invited you. If you add your code (from above) you will be a collaborator to the project.

https://github.com/jenstornell/kirby-splitview-panel-bar.git
