### ISSUE TITLE
Flip switch

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#17]
## Hide is nice but...

When tried it alot I really like the hide feature, except for an issue I already reported.

I found out that there is another thing needed. Sometimes the panel bar is in the way, and I want to move it out of the way but still keep it accessible.

## Flip switch

The easiest way to move the sidebar out of the way, without hiding it, would be to move it to top or bottom depending on where it is right now.

## Option still important

We have an option if it should be at the top or at the bottom. I think it's still important that it work that way because it desides what it should do on load.

**Comment by distantnative** [comment]
It's on the dev branch.
