### ISSUE TITLE
Hide button - line to the left?

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#18]
The items in the bar have a line separation, but not the hide button. I think it should. Else it almost looks like it's a part of logout.

The line to the left should only be there when the menu is shown, not when hidden.

**Comment by distantnative** [comment]
Can you post a screenshot?
I seem to have all of them:

<img width="1119" alt="screen shot 2015-09-04 at 15 42 08" src="https://cloud.githubusercontent.com/assets/3788865/9684992/8ec9322a-531b-11e5-8ee0-c7cac5ec8ee0.png">

**Comment by distantnative** [comment]
Ahh sorry, just after commenting I realized that you don't mean the visible/invisible switch, but the x-btn

**Comment by jenstornell** [comment]
Yes, I mean the X-button. Looking forward to it.

**Comment by distantnative** [comment]
Also solved on the dev branch.
