### ISSUE TITLE
Missing line?

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#182]
After "Add" there is no line. It's a choice to make if you want the line or not.

I see it like this. You cannot click all the way to the right. It does not tell where the "Add" button ends so because of that I think an ending line would be most "correct".

![image](https://cloud.githubusercontent.com/assets/927011/12481413/42eb26ce-c049-11e5-8e8d-c95fd5c25c58.png)

**Comment by distantnative** [comment]
Quick answer: It's intentional - will think some more about if it should stay like that tho.

**Comment by jenstornell** [comment]
How it works now we don't see where the last button ends. It blends with the bar.
