### ISSUE TITLE
Can't use c::get when extend \panelBar\Element

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#183]
**This code:**

```php
<?php
namespace panelBar\Elements;
use panelBar\Pattern;

class Splitview_link extends \panelBar\Element {
	public function html() {
		return pattern::link(array(
			'id'      => $this->getElementName(),
			'label'   => 'Splitview',
			'icon'    => 'columns',
			'url'     => $this->site->url() . '/' . c::get('splitview.route', 'splitview') . '/?page_slug=' . urlencode($this->page->uri()),
			'compact' => true,
		));
	}
}
```

**...gives...**

Fatal error: Class 'panelBar\Elements\c' not found in C:\wamp\www\kirby2.2\site\plugins\splitview-panel-bar\splitview-panel-bar.php on line 11

**Loads from config.php**

Maybe it's the load order or just not allowed in the scope? I setup the panelBar in the config.php.

**Comment by distantnative** [comment]
You just have to add

```
use C;
```

before the class.

**Comment by jenstornell** [comment]
It works! I'm closing it, but it can be good to have in the docs?
