### ISSUE TITLE
panel-bar setup in footer

### ISSUE THREAD

**Issue by m-artin** [distantnative/panel-bar#192]
Not quite sure, if this is an issue. 

The setup instruction on github doesn't work for me with this line of code. 
`<?php snippet('plugin.panelBar') ?>`

But it does work with the following line included in the readme file. 
`<?php echo panelBar::show() ?>`

(Latest Kirby version and tested on localhost by the way.)

**Comment by distantnative** [comment]
Could you try it with the most current version from the `develop` branch? It should work just like `<?php snippet('plugin.panelBar') ?>`
