### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by samnabi** [distantnative/panel-bar#203]
v2.0.0 seems to have removed the GPL license that was shipped with v1.0.1.

Is this repo still distributed under GPL, or is there a new license?

**Comment by distantnative** [comment]
I put other plugins under MIT license and consider this for panelBar as well (thx for pointing out that the info is missing). To be honest, I have a hard time understanding the details and differences as I do not really care XD Happy to her if there is an argument against MIT and for keeping GPL!

**Comment by samnabi** [comment]
The main difference is that MIT is less restrictive. With GPL, any forks or derivative works have to release their source code.

**Comment by distantnative** [comment]
Ok, I guess then I will keep the decision to go with MIT – it's okay for me if e.g. theme developer include this plugin but don't want to release their to-be-paid theme code. I will include the LICENSE file and a mention in the README in the next release 👍

**Comment by jenstornell** [comment]
When I worked with WordPress they used GPL which created some problems. It was not possible have sub-licenses. For example I could not release a plugin for WordPress with MIT license. It had to be GPL as well. Else they would not work together legally if I remember correctly.

I agree with you both that MIT is THE license for free stuff that only reqiure the license to be kept in the package. :thumbsup:
