### ISSUE TITLE
Installation broken

### ISSUE THREAD

**Issue by olach** [distantnative/panel-bar#213]
Tried installing this plugin with no luck.

I tried to install via the CLI:

    kirby plugin:install distantnative/panel-bar

Then I added this snippet to my `footer.php`.

    <?php snippet('plugin.panelBar') ?>

But nothing shows up in frontend or the panel. Then I read the manual installation instructions that says that the plugin needs to be in the folder `site/plugins/panel-bar`. But when I installed using the CLI the folder name is `site/plugins/panelBar`. When I rename the folder to `site/plugins/panel-bar` the plugin seems to be activated, but the frontend just generates a lot of errors, and in the panel, the Panelbar widget shows this error:

    array_diff(): Argument #2 is not an array

Did I miss something obvious that is needed to correctly install this plugin?

**Comment by distantnative** [comment]
Just published 2.1.2 with two fixes that should solve both problems that you have encountered. Thank you for pointing them out! (and no, you did everything right, those were my bugs)
