### ISSUE TITLE
Interferes with Kirbies JS loader

### ISSUE THREAD

**Issue by CodeStalker** [distantnative/panel-bar#223]
If I use the Kirby JS autoloader **after** Panelbar snippet, it breaks the loader. It seems to load the javascript from the default template on all pages of the site, rather then the actual one for the page.

This works:

```
<?php snippet('site-js', ['staging' => 'testdomain.dev']) ?>
<?php snippet('plugin.panelBar') ?>
```

This breaks the loader:

```
<?php snippet('plugin.panelBar') ?>
<?php snippet('site-js', ['staging' => 'testdomain.dev']) ?>
```

My snippet contains this:

```
<?php
$pageurl = $_SERVER['HTTP_HOST'];
if (strstr($pageurl, $staging)) {
    echo js('/assets/js/common.min.js');
    echo js('@auto');
} else {
    echo js('/assets/js/common.js');
    echo js('@auto');
}
```
I'm using the development branch version of Panelbar.

**Comment by distantnative** [comment]
Fixed on the newly released 2.3.1
