### ISSUE TITLE
Non-image files lead to exception in list.php

### ISSUE THREAD

**Issue by awenro** [distantnative/panel-bar#224]
Kirby Toolkit | v2.4.1
Kirby CMS | v2.4.1
PHP 5.6.19 – local environment :sweat:

Steps to reproduce: 
1. Add non-image file (e.g. pdf, doc) to files
2. Open page in frontend

PrettyPageHandler throws the following error: _Undefined index: image_
_/plugins/panel-bar/elements/files/templates/list.php_

```
<div class="panelBar-files__image" <?php e($item['type'] === 'image' and isset($item['image']), 'style="background-image:url(' . $item['image'] . ');"') ?>>
```

**Comment by distantnative** [comment]
You can find a fix now on the develop branch
