### ISSUE TITLE
Panelbar helper as plugin?

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#28]
It would be nice to create a custom panel helper as a plugin. I don't know if it could work with:

    panelbar::my_helper();

I'm not sure about how the singleton work fully.

It means plugins for this plugin.

**Comment by distantnative** [comment]
Not that I'd be aware of a way to do this.

You can of course always just create a normal function and re-use this for several elements:

```php
function custom($text) {
  return '<div>'.$text.'</div>';
}

c::set('panelbar.elements', array(
  'panel', 
  'edit',
  'custom-1' => custom('hallo'),
  'custom-2' => custom('bye'),
  'logout', 
));

```

**Comment by jenstornell** [comment]
Ok then. We cannot use like this:

    panelbar::my_helper();

But maybe we should recommend another standard for plugins, like some of these maybe?

    panelbarMyHelper();
    panelbar_MyHelper();
    panelbar__MyHelper();

**Comment by distantnative** [comment]
I like all of them :D
