### ISSUE TITLE
Dev branch - Logout moving

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#29]
When starting the panel in development branch the logout item has fallen down. When I hide the bar and then show it again it places where it should. Maybe some HTML render is different somehow. Some class name that differs?

**Comment by distantnative** [comment]
Can't reproduce that error. Which browser are you using?

**Comment by jenstornell** [comment]
### Before clicking hide

![before](https://cloud.githubusercontent.com/assets/927011/9733241/eb13504a-5629-11e5-8a33-81e7f82c2543.png)

### After hide and show again

![after](https://cloud.githubusercontent.com/assets/927011/9733244/f9a3268a-5629-11e5-9a76-0d791f0969fb.png)

Using Google Chrome, latest version.

**Comment by jenstornell** [comment]
Tried some more. If in developer tools uncheck "Float: right" and then check it again it places correctly. I don't know if it has something to do with JS and CSS order.

**Comment by jenstornell** [comment]
Sorry for spamming. I just found out what made the error.

    <script src="http://fast.fonts.net/jsapi/fe9ffbe3-c785-40ec-9527-b8192e270fb8.js"></script>

I use fonts.com for a font and when deleted the script above it works again. A little strange because it's the first time I got in trouble because of it.

**Comment by jenstornell** [comment]
I added info to the docs and closing it.
