### ISSUE TITLE
Question - Preview feature too big?

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#36]
Here is more of a question. Is the "Preview" feature to big to be built into the panel-bar project? I wrote down some issues in a previous comment.

I have found even more problems like:

- When panel-bar at the bottom the CSS might not work as expected.
- When page is updated there is a flickering (blinking). I don't mind a delay of the updated content but the blinking makes me blink. I think it's possible to go around with some more work, like only update the body with updated HTML. That would require some Ajax as well.

So, will the preview feature be to big for the panel-bar project? Should it be made as a standalone plugin? Or should it be made as a standalone files in this plugin to separate them, to avoid messyness?

If you feel it's too big I can try to build it as an own plugin but if you still want to continue the development I will leave it to you. Just let me know.

**Comment by distantnative** [comment]
Just copying it over to the other issue and closing it here, to have preview as only one issue right now. I'm still interested in the idea and will work on it when I got time - it's just really hackish, so I have to see if I find cleaner ways or not.
