### ISSUE TITLE
When using mobile => 'text' a padding left is missing

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#39]
When using ''mobile" => 'text' a padding left is missing in mobile mode. However, should the icon be visible on mobile if "text" is set? I expected only the text to be shown.

**Comment by distantnative** [comment]
Should be mobile => 'label'

**Comment by jenstornell** [comment]
Yes, it works. Might be missing docs. It does not say right away what choices there is to the "mobile". It's because it is a choice between two states.

The rest is self explaining by the examples but not "mobile".

**Maybe just add this in the example on the mobile row:**

    //States: "icon" or "label"

**Comment by distantnative** [comment]
Won't do it for now, cause I don't like the current state of how responsiveness is handled (or not handled). So I'm sure that this will change pretty soon (and the mobile option probably will be different or vanish).

**Comment by jenstornell** [comment]
Sometimes we want the icon and sometimes the label. That part will not change, if it's going to work the way it is now. On edit we always want the icon, but for loadtime it could not work at all with the icon. I'm a little bit afraid of the "vanish" solution here.

Maybe you have something totally different in mind? I just hope it's not getting poor.

**Comment by distantnative** [comment]
No, with "vanish" I meant just the option in the way it's implemented now. There should always be a way to decide whether to show icon or label when little space.
