### ISSUE TITLE
panelbar:: not available in config.php

### ISSUE THREAD

**Issue by distantnative** [distantnative/panel-bar#4]
Sadly, the panelbar class does not seem to be ready yet when called in the `config.php`:

```
Fatal error: Class 'panelbar' not found in /Users/nhoffmann/Development/Kirby/dev/site/config/config.php on line 81
```

Looking for a workaround.

**Comment by jenstornell** [comment]
I just saw that too. :(

**Comment by distantnative** [comment]
It still works if you define it right in your snippet/template. Or when not using the helper methods. Will try to find a way to also use them in config.php

<img width="1079" alt="screen shot 2015-09-04 at 10 04 41" src="https://cloud.githubusercontent.com/assets/3788865/9679166/651450f6-52ec-11e5-8e83-36772f0f856e.png">

**Comment by distantnative** [comment]
Any idea how I could get plugin functionality to the `config.php`, @bastianallgeier?

**Comment by jenstornell** [comment]
Does it work if adding this before in the config file?

    kirby()->plugin('panel-bar');

I can test it in a few hours when at work.

**Comment by distantnative** [comment]
Yes, that works! :+1:
