### ISSUE TITLE
Don't use CDN for font awesome

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#40]
It can be good to use CDN for speed and so on. In this case i think it would be better to have it on the local environment.

**Advantages of having it on local**

- It does not rely on that the internet works (when working on localhost for example)
- It does not rely on that the server of font awesome is up.
- It does not rely on that we do too many requests to the font awesome server.

If you don't want to add it to the github project because of license or so, just hotlink to it in the installation instructions.

Feedback?

**Comment by distantnative** [comment]
Not to myself: try to point towards the panel's files

**Comment by jenstornell** [comment]
+1

**Comment by jenstornell** [comment]
Nice! I just found out that there might be a future possible problem here. We can change the folder structure in Kirby (I have not looked into how far). If the plugin folder changes the level in compare to the panel, this would not work anymore.

Might not be a problem today.

To get around it, get config server urls / paths and generate font CSS dynamically?

**Comment by distantnative** [comment]
Wouldn't know how to get sever urls/paths into the (S)CSS - any idea?

**Comment by jenstornell** [comment]
Here comes a very ugly code that don't work. I hope you can see the idea:

```php
$fonts = $kirby->roots()->index() . '/panel/fonts/a-font.ttf';
$fonts .= $kirby->roots()->index() . '/panel/fonts/a-font.otf';
$css .= $fonts . $css;
return $self->__output($css, $js);
```

It's far from working but first add fonts with correct paths in the PHP before CSS output. Then just before output merge the fonts to the CSS string.

This way the fonts are not added to the SCSS. I don't know if it's important to have them there?

**Comment by distantnative** [comment]
Done :)
