### ISSUE TITLE
I made a plugin for loading time

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#41]
It's so small so I have just made a GIST so far. The first panel-bar plugin is created! Works great!

https://gist.github.com/jenstornell/c4990a30eedd1dd69e6a

**Docs:**

Add a list with panel-bar plugins somewhere in the docs?

**Comment by distantnative** [comment]
Would you mind if I integrate it as as a default element?

**Comment by jenstornell** [comment]
Do it! ☺ Then I have one less plugin to keep updated.

**Comment by distantnative** [comment]
:+1:
