### ISSUE TITLE
Helper / element - Edit images

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#43]
I lifted out an idea from here:

https://github.com/distantnative/panel-bar/issues/23

An edit image helper / element. A list or a gallery with the images attached to the current page.

To not make it load when not in use, add the images as background images. Then they will only render when "dropdown" is visible. Maybe also limit the images to the 25 latest and a "more" link to edit the page. That way you don't need to paginate the gallery.

Should it be implemented or does it fit better as an external plugin?

Feedback?

**Comment by distantnative** [comment]
Not sure how this would look like? Wouldn't that be just a huge dropdown?

**Comment by jenstornell** [comment]
If dropdown as list it would probably be like...

[image] - Filename
[image] - Filename

If dropdown as gallery it would be more like
[image][image][image]
[image][image][image]

The last one is a space saver but the first one is with more information.

Then as I said, there might be 200 images on one page. Limit to 25 with a "more" button?

If you want to add this field type I recommend to have the images as background images so they are generated when they are visible.

Should it be built in or as a plugin do you think?

**Comment by distantnative** [comment]
> If you want to add this field type I recommend to have the images as background images so they are generated when they are visible.

Does this really make it difference - since we are on the page, shouldn't the images be loaded and rendered anyways in the content?

**Comment by distantnative** [comment]
A lil sneak...
<img width="589" alt="screen shot 2015-09-15 at 18 21 13" src="https://cloud.githubusercontent.com/assets/3788865/9882761/a22df58a-5bd6-11e5-9f65-e69557dbb174.png">

**Comment by distantnative** [comment]
First approach is on the dev branch.

**Comment by jenstornell** [comment]
http://webmasters.stackexchange.com/questions/2280/how-to-pre-load-images-used-only-on-hover

Here it is but the op has it as an issue that the background loads ay first when hover.

**Comment by jenstornell** [comment]
I will try it out on thursday ar 13. Edge case would be mobile device with 100 images and see what happends.

**Comment by distantnative** [comment]
Haha, can already tell you that mobile device will fail. Not yet responsive.
