### ISSUE TITLE
Panel Bar and activated cache

### ISSUE THREAD

**Issue by servicethinker** [distantnative/panel-bar#44]
Seems like that the Panel bar will be also shown when the standard kirby cache is activated. It's still there when I'm logged out.

It seems like that this is a main problem of the cache driver.

**Comment by jenstornell** [comment]
Is this really a panelbar bug? I think it's a Kirby issue, that is caches pages even when logged in.

We might want many elements viewed when logged in, not just the panelbar. In that case we need to somehow only cache pages when user is not logged in.

**Comment by servicethinker** [comment]
That's what I mean with "main problem of the cache driver", because I had similar problems in other projects.

Thanks for the solution :+1: . Could you give more informations? Where I have to insert your snippet? In the config file?

**Comment by jenstornell** [comment]
Ooops. I forgot a ! there. Yes of course you are right, the cache should only be active when the user is NOT logged in.

Thanks for correcting me!
