### ISSUE TITLE
Is it BEM SCSS?

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#46]
Are you using BEM? I read about it in the last few days.

http://getbem.com/

I'm going to start using it to get organized. The resistance people think that it's an ugly syntax but I think it looks nice.

Is it BEM in panel-bar SCSS files?

**Comment by distantnative** [comment]
It's BEM-ish so far. But yea, goal is to get it more consistent with BEM

**Comment by distantnative** [comment]
Changed a bit: https://github.com/distantnative/panel-bar/commit/0ea41fe18003f7570a1833840a7f218db181e752

Style classes are now like:
.panelbar-element
.panelbar-label
.panelbar-drop
.panelbar-box
…

elements of these main element are like:
.panelbar-drop__list

and identifier are:
.panelbar--[WHATEVERID]

**Comment by distantnative** [comment]
Urgs... I think I broke something :P
