### ISSUE TITLE
Development - Inline args in template don't seem to work anymore

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#48]
I got wierd bugs when I try to use the configs in config.php. Using this made other function stop working: kirby()->plugin('panel-bar'); Therefor I have it in the template instead like this:

```php
<?php
$items = array(
	'panel',
	'add',
	'edit',
	'update' => panelbar::link(array(
		'id'     => 'panel',
		'icon'   => 'rotate-right',
		'url'    => site()->url() . '/update-kreditgivare/?update=true',
		'label'  => 'Sync',
		'mobile' => 'icon',
	)),
	'logout'
);

echo panelbar::show( $items );
?>
```

It worked before but does not for me anymore. It sets default instead.

When using c::set it works but as I said, other functions stop working when using the forced plugin loader.

**Comment by distantnative** [comment]
What version are you using? the most current from the dev branch?

**Comment by jenstornell** [comment]
Yes, I used the download button to get all the files, from the development branch.

**Comment by distantnative** [comment]
Be aware of this change then: https://github.com/distantnative/panel-bar/commit/2ddcaab282bdca7542d8806ad00f2adbff71832e

So it would be 'echo panelbar::show(array('elements' => $items))`

**Comment by jenstornell** [comment]
Now it add my custom "update" feature, but it also load all the default stuff for example "Invisible".

```php
<?php
$items = array(
	'panel',
	'add',
	'edit',
	'update' => panelbar::link(array(
		'id'     => 'panel',
		'icon'   => 'rotate-right',
		'url'    => site()->url() . '/update-kreditgivare/?update=true',
		'label'  => 'Sync',
		'mobile' => 'icon',
	)),
	'logout'
);

echo panelbar::show( array( 'elements' => $items ) );
?>
```

**Comment by jenstornell** [comment]
I downloaded dev version and it seems to be working now.

**Comment by distantnative** [comment]
:+1: - still need to include a default elements set instead of all existing
