### ISSUE TITLE
Development - Not everyting as default?

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#49]
Now it seems like every feature (element) is added as default. There might be more elements in the future and I think it's good to already narrow down the default stuff.

**In my world these are the important ones (as default):**
- Panel (home is a must)
- Add
- Edit
- Files (does more than images)
- Loadtime (I love this myself but I don't know about others)
- User (who is logged in, yes important)
- Logout

**The onces I don't added was:**
- Invisible (maybe many use this, I don't)
- Images (files are almost the same and lists all. No need for both)

Loadtime and invisible are the onces I'm not sure how the rest of the world think. The other stuff I'm confident. What do you think?

For some feature-crazy guy it might be good to have the option to show "default" or "all". I don't know how an option like that would look like.

**Comment by distantnative** [comment]
I set this for the moment this way, cause it allows me to quickly add element functions when developing. I will change this before a next release.
