### ISSUE TITLE
Development - Room for 6 images, showing 4

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#50]
Development - Room for 6 images, showing 4

![image](https://cloud.githubusercontent.com/assets/927011/9934942/5b94f662-5d54-11e5-9df8-74ffd15f07e9.png)

**Comment by distantnative** [comment]
Just to help me find the bug faster: are there only 4 files for this page or at least 6? (also weird that it doesn't show the label with the SVG file extenstion in the center)

**Comment by jenstornell** [comment]
It's just 4 files in total.

**Comment by jenstornell** [comment]
I still got the same bug. Downloaded development branch.

**Comment by distantnative** [comment]
Really weird, cause then it doesn't seem to be a CSS issue as I thought, but something wrong with the coun PHP part.

**Comment by jenstornell** [comment]
Are the files really uploaded to the repository? Are the SASS compiled, and uploaded?

**Comment by distantnative** [comment]
Yes, they are. All SCSS files and JS files are constantly compiled and uploaded. So that can't be the issue.

**Comment by distantnative** [comment]
I will close this for now as many changes are made to the fileviewer. If the issue still exists afterwards, please just open a new issue :)
