### ISSUE TITLE
Dev - Images suggestion - Square format

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#51]
Now the images are maybe 4:3 in size. They would not be perfect in the format 1:1 and will look really bad in 3:4.

There are three main formats, standing, lying and square. To make the best fit use 1:1 (square) because it's in between 4:3 and 3:4, like Instagram.

**Comment by distantnative** [comment]
The problem is that our screens are usually wider than tall - using 1:1 would result in less images visible in the dropdown. I think, I'm quite okay with 2:3 atm.

**Comment by jenstornell** [comment]
You changed background-size to contain and that fixes the main problem so I'm totally fine with it.
