### ISSUE TITLE
Dev - Images suggestion - No label overlap

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#52]
Now there is a gradient with black and a label that overlaps the image. It's probably for saving space.

I still perfer the label to be below the image, not above it, like when editing the images in the panel.

**Comment by distantnative** [comment]
I tried a few things, but I actually realized that I like it overlapping the best for the moment. Set out a milestone v1.1 to revise the whole image/file element

**Comment by distantnative** [comment]
After working a day on the fileviewer with labels below, I realized that I really don't like how much space that takes up and put them back overlapping (tho with no gradient):

<img width="745" alt="screen shot 2015-10-11 at 19 28 28" src="https://cloud.githubusercontent.com/assets/3788865/10417981/8fb0ad1c-704e-11e5-80d1-aa95b8bded90.png">

**Comment by jenstornell** [comment]
I like them!
