### ISSUE TITLE
Responsive: slider for element scrolling

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#54]
When too many things in the bar it might not be the best to have them like bricks on top of each other. A few ideas how to solve it.

- Overflow-z: scroll; (css. Probably the most simple solution)
- Make dropdown (might be difficult because the elements have dropdowns of themselves)
- Slider, like show 3 elements at the time and have arrows left and right to slide it.

**Comment by distantnative** [comment]
Dropdown doesn't seem right. `overflow-x: scroll` sadly automatically sets `overflow-y: hidden` and that ruins all dropdowns. Will see if a slider works.

**Comment by distantnative** [comment]
Tried it, doesn't really work well. Will  leave it with icons being hidden on too narrow screens. Tho, there you can pass parameters now to the builders to hide elements either on mobile or on compact view (compact => when even the mobile elements are too wide for the screen):

```php
  Build::link(array(
      …,
      'mobile'  => false,
      'compact' => false,
      'float'   => 'right',
    ));
```

**Comment by jenstornell** [comment]
Overflow: scroll hides the dropdowns? Maybe it's possible to add z-index to get them on top? With some combination for position: absolute? And position relative on it's parent?

**Comment by distantnative** [comment]
No, not really sadly. z-index doesn't help due to the chain of positioned elements: fixed > relative > absolute... 
Only idea which I'm not sure would work: Could position the dropdown as fixed again when in compact view, and simply make the dropdown center the screen. Cause in fixed, I don't see a way to determine how to put the dropdown under its element. On narrow views (like compact) might not be such a problem.

**Comment by jenstornell** [comment]
It seems like a hard one. Just don't make a mess of the CSS. The less you can use position: absolute, the better I think.

**Some other ideas:**

- Just add "Go to panel" on mobile devices panel. Then it's not ment to use the panelbar that much on a mobile.
- Just add the features without dropdowns "Panel" and "Edit" and "Loadtime". Hide the features that are hard on mobile devices.
- Add an alternative set of elements when on mobile resolution. If the user sets 30 elements, it's that persons fault.

**Comment by distantnative** [comment]
I actually like the first idea, cause you don't really need the panel bar on mobile and it would clean up a lot of the code (mainly css). Thinking about it.

**Comment by distantnative** [comment]
Went with it :)

**Comment by jenstornell** [comment]
Awesome, so simple!
