### ISSUE TITLE
Dev - Images suggestion - background-size: contain?

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#55]
In my images I have some heads cut off. That's because of the background-size: cover. Using background-size: contain; will keep the images in it's box.

**Advantages with cover:**
- Images are zoomed in.
- The box is filled with content.

**Advantages with contain:**
- The whole images are seen. Good for example if two images are almost identical but differs at the top. Then it's easy to see which one is which.
- It's easy to see what format the image is.
- No heads are cut.

I like the contain better because the function play a bigger role than design here, I think.

**Comment by distantnative** [comment]
Moved to `background-size: contain` - still needs some design work.

**Comment by jenstornell** [comment]
Nice! Remove the black bakground and it's complete?

**Comment by distantnative** [comment]
:+1:

**Comment by jenstornell** [comment]
Did you remove the black background? I still have it from the latest development branch.

**Comment by distantnative** [comment]
No, it looked bad with a white background imho. I'll work on the whole fileviewer on a later point in time
