### ISSUE TITLE
Fileslist view

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#56]
When viewing images it's nice to have them as a gallery, but when chosing to list files I'm not so sure. There can be files of all types, PDF, DOCX, ZIP whatever.

My suggestion is to have files as a list instead of gallery.

**Comment by jenstornell** [comment]
What happend to this? For me my files and images are both as gallery. Is it ment that way?

**Comment by distantnative** [comment]
Just use the `filelist` or ìmagelist` elements instead of `files` or `images`:
<img width="415" alt="screen shot 2015-10-16 at 11 57 55" src="https://cloud.githubusercontent.com/assets/3788865/10539061/2b8a8d82-73fd-11e5-8f5c-5fbafe87b532.png">

**Comment by jenstornell** [comment]
Awesome! I totally missed that one!
