### ISSUE TITLE
CSS a little buggy

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#57]
- Someting with the CSS makes a grey box.
- Small buttons to the right have jumped up.
- The line is too tall between the little boxes.
- Logout comes too times.

![image](https://cloud.githubusercontent.com/assets/927011/9936270/640e5ee4-5d5b-11e5-8c4b-350fc9b65b5f.png)

```php
<?php
$items = array(
	'panel',
	'add',
	'edit',
	'update' => panelbar::link(array(
		'id'     => 'panel',
		'icon'   => 'rotate-right',
		'url'    => site()->url() . '/update-kreditgivare/?update=true',
		'label'  => 'Sync',
		'mobile' => 'icon',
	)),
	'logout'
);

echo panelbar::show( array( 'elements' => $items ) );
?>
```

**Comment by distantnative** [comment]
I think I fixed parts of it (multiple logout buttons) and will work on the other bugs as soon as I'm tackling responsiveness anyways.

**Comment by jenstornell** [comment]
It seems to work now.
