### ISSUE TITLE
Toggle the panel bar

### ISSUE THREAD

**Issue by distantnative** [distantnative/panel-bar#6]
@jenstornell wrote:
>Now I know why I always turn off the bar in WordPress. It's often in the way at the top and adds too much bloat in the HTML.
>
>I still belive in a panel bar if it's flexible as hell.
>
>Make it possible to hide it whenever you want with a "+" toggle-button or so. When hidden, just leave a fixed toggle-button to be able to show it when ever needed.
>
>Make use of panelbar::hide(). When using this function the panel can be hidden on load. Just a toggle-button visible. When using panelbar:show() it can be visible on load.

Random thought: The panel bar would be visible every time the page loads new, @jenstornell? Cause I'm not sure if I'd really want to store the toggle information in a cookie or so. Ideas?

**Comment by jenstornell** [comment]
My idea here was simply:

**Visible on load:**

    panelbar::show(args)

**Hidden on load:**

    panelbar::hidden(args)

If my choice is to use panelbar::hidden() I chose to not see the panel at first site, just a toggle-switch.

No need for cookie or storing stuff.

**Comment by distantnative** [comment]
Okay, but if you use

```
panelbar:show()
```

The bar would be visible on load, could be hidden by pressing the switch, but visible again as soon as the page reloads / loads another page?

**Comment by jenstornell** [comment]
Yes.
