### ISSUE TITLE
About ids

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#60]
When using default stuff like "add" or "edit" it's natural to just add them like now.

Then I have the key "update" with the id "panel". What does the key "update" do, except for just making the array key unique? Nothing I guess? Can't the key also be the ID instead then?

Else it can be confusing what the ID and what is not. Removing "id" and using the key instead would also make the args shorter and more readable.

Here I have keys and ids that does not match.

```php
$items = array(
	'panel',
	'add',
	'edit',
	'update' => panelbar::link(array(
		'id'     => 'panel',
		'icon'   => 'rotate-right',
		'url'    => site()->url() . '/update-kreditgivare/?update=true',
		'label'  => 'Sync',
		'mobile' => 'icon',
	)),
	'test' => panelbar::box(array(
		'id'     => 'panel2',
		'icon'   => 'rotate-right',
		'label'  => 'Testing box',
		'content' => '<div class="test" style="background: red;">icon</div>',
	)),
	'logout'
);

echo panelbar::show( array( 'elements' => $items ) );
```

**Comment by distantnative** [comment]
Problem is that e.g. `panelbar::link()` already generates the HTML code with the ID included and then gets added to the array. I don't think there is a way for `panelbar::link()` to be aware of the key of this array. Or do you have any idea how that would be possible?

**Comment by jenstornell** [comment]
Ahh, I did not see that one coming. But now I understand why it's there.

I have no idea how to solve it. The problem is not the `id` in this case. The problem is having two "ids" and not knowing which does what.

But still no, I have no good solution for it right now.

Maybe set it as "Help needed" if some megamind comes up with an idea?

**Comment by distantnative** [comment]
True. Also you don't need to have them both. This should also work:

```php
$items = array(
    'panel',
    'add',
    'edit',
    panelbar::link(array(
        'id'     => 'panel',
        'icon'   => 'rotate-right',
        'url'    => site()->url() . '/update-kreditgivare/?update=true',
        'label'  => 'Sync',
        'mobile' => 'icon',
    )),
    panelbar::box(array(
        'id'     => 'panel2',
        'icon'   => 'rotate-right',
        'label'  => 'Testing box',
        'content' => '<div class="test" style="background: red;">icon</div>',
    )),
    'logout'
);

```

**Comment by jenstornell** [comment]
I was going to write it just like that, but figured that it wouldn't work, but if it does it's great, I think.

**Comment by jenstornell** [comment]
I just had a few minues and it does work. Maybe just update the docs on this one?

**Comment by distantnative** [comment]
Actually, I just found a way. Now this works:

```php
<?php
function customDropdown() {
  return panelbar::dropdown(array(
    'icon'  => 'headphones',
    'label' => 'Songs',
    'items' => array(
      array(
        'url'   => 'https://www.youtube.com/watch?v=BIp_Y28qyZc',
        'label' => 'Como Soy'
      ),
      array(
        'url'   => 'https://www.youtube.com/watch?v=gdby5w5rseo',
        'label' => 'Me Gusta'
      ),
     )
  ));
}

$elements = array(
  'panel',
  'edit',
  'mum'   => panelbar::link(array(
    'icon'  => 'heart',
    'url'   => 'http://mydomain.com/pictureofmum.jpg',
    'label' => 'Mum'
  )),
  'songs' => 'customDropdown',
  'logout',
);

echo panelbar::show(array('elements' => $elements));
?>
```
