### ISSUE TITLE
Config to add jQuery

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#65]
Might be handy to add an option to include jQuery.

```php
c::set('panelbar.loadjQuery', true);
```

This would load jQuery right before the panelbar scripts. It would only load jQuery when logged in.

Default would be to have this setting to false, probably.

**Comment by distantnative** [comment]
Hmm torn about this one. Don't really like the idea to also add this library through the plugin - why not just add it yourself, instead this line to the `config.php`. On the other hand, it would only be loaded when logged in.

**Comment by jenstornell** [comment]
I just got rid of all my jQuery code and it feels great to add 5kB (jQuery DOM alternative) instead of 85kB (jQuery).

However I still want to run the panelbar, but in this case it might not be the best to have it magically but to include it ourselves.

Optimal would be to have the panelbar independent from jQuery but that might be alot of work.

Close this if you want.

**Comment by distantnative** [comment]
I will probably rather aim for the jQuery-independent version.

**Comment by jenstornell** [comment]
That would be best. It would also make the enhancedjs option unneeded.
