### ISSUE TITLE
Remember current state

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#66]
I've been in a situation where I wanted the panelbar to remember the current state. That's because I refreshed alot during site development.

I have an idea for it. This in the config.php as default:

```php
c::set('panelbar.rembember', false);
```

If set to true it stores the `position` and the `show/hide` as JS localstorage. I think there no need to go overboard with an ajax, cookie, session or so. Just a localstorage. It's simple to use.

To make it still respect the config.php, save a timestamp in the localstorage as well. Then it could be active for 24 hours and then fall back to config.php after that.

Feedback?

**Sidenote:**

I see you have not added stuff here in a while. Maybe you have not had the time, or maybe you feel flooded by my issues? A good thing however is that I think my issues are quite small and it's hard to figure out more good features for it. I think its close to beeing "complete".

**Comment by distantnative** [comment]
Quick reply: Like the idea! And don't worry, I like most of your issues, it's just simply that at the moment I have to really put a lot of work into making a living and haven't had time in a while to devote to this plugin :/

**Comment by jenstornell** [comment]
I just bought a moral license with about 50 dollar for all your work so far. I hope you can survive an hour or two with it.

**Comment by distantnative** [comment]
Thanks, I really appreciate your support!

**Comment by distantnative** [comment]
I just added it to the dev branch :) - let me know if it works for you!

**Comment by jenstornell** [comment]
Don't work for me. If I toggle the position and reload nothing happends. If I close the page refreshes.

I set this in config.php:
```
c::set('panelbar.remember', true);
```

**Comment by distantnative** [comment]
What browser, OS etc. are you using? Any JS errors?

**Comment by jenstornell** [comment]
Windows 10, Google Chrome. I have hard to belive it's environmental related (as it's not IE).

**Comment by distantnative** [comment]
Can't reproduce it, works in all my tests (firefox, chrome, safari on mac os) - do you have localstorage deactivated somehow?

**Comment by distantnative** [comment]
Still not working for you?

**Comment by jenstornell** [comment]
No. I also get `undefined` on all these after clicking the position button.

```js
console.log(localStorage['panelbar.expires']);
console.log(localStorage['panelbar.position']);
console.log(localStorage['panelbar.visible']);
```

**Comment by distantnative** [comment]
How about now, switched from

```javascript
localStorage['panelbar.expires']
```

to using

```javascript
localStorage.getItm('panelbar.expires)
```

**Comment by distantnative** [comment]
How is it working with the current develop branch?

**Comment by jenstornell** [comment]
It does not work. Not even javascript errors. Is this still correct?

```
c::set('panelbar.remember', true);
```

I have my panelbar settings array in my template instead of config.php. Does it matter?

**Comment by distantnative** [comment]
Oh my god, just found the embarrassing typo: `c::set('panelbar.remebmber', true);`instead of `c::set('panelbar.remember', true);` :( :( :(

Just fixed the typo, sorry. Does it work now for you?

**Comment by jenstornell** [comment]
For the first time it does! Cool!

**Comment by distantnative** [comment]
Yay! Sorry for that stupid bug.
