### ISSUE TITLE
Panel add / edit - In an iframe?

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#67]
When clicking the edit button then we are leaving the page. There is no "Close panel and go back to the page".

An idea for it is to have the panel in an iframe floating on top of all things. Then the panelbar could be "attached" to it. It would allow to close the panel and go back to the site again, even without a page reload.

Like a lightbox or modal for the panel, but in fullscreen to use all the space.

Feedback?

**Comment by distantnative** [comment]
Added to the dev branch

**Comment by jenstornell** [comment]
Don't work well here. The menu bar disapears.

**Comment by distantnative** [comment]
the panels top/menu bar is intentionally hidden as I think it doesn't make much sense within this use combined with the panel bar.

**Comment by jenstornell** [comment]
Ahh, I had this issue (iFrame doesn't work with panelbar.bottom):
https://github.com/distantnative/panel-bar/issues/73
