### ISSUE TITLE
Increase z-index on bar

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#74]
Never ever do we want something to be on top of the bar or the iframe.

**Maybe change this:**

    z-index: 1001;

**To this:**

    z-index: 1000000000;

Personally I use up to a million in z-index, and my topmenu was on top of the bar.

**Comment by distantnative** [comment]
I will increase the z-index, but am wondering if such a high number is reasonable at all.
Personally, I'd feel rather linke `999900`

**Comment by jenstornell** [comment]
Where does 999900 come from?

http://www.puidokas.com/max-z-index/
Maybe 16777271?

**Comment by distantnative** [comment]
Ok, maybe something around `2147483647` as Safrai 3 would fallback to its max value anyway... I like clean numbers with a little space to the top in case, I'd need a little higher z-index for something else, so `2147483000`?

**Comment by jenstornell** [comment]
Yes, I would be 100% happy about that.
