### ISSUE TITLE
Loading when closing the edit iframe?

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#75]
This might just be a question, maybe an issue. When I close the edit iframe it loads a while before my page is back. It does not just close the iframe?

In my developer tools I `display:none` the iframe and my page shows instantly fast.

**Comment by distantnative** [comment]
Yea, but without the changes you just did in the edit iframe (I mean, that's what it is for, right?)

**Comment by jenstornell** [comment]
Ahh, that explains it. Really good reason. Nice work!

If no change has done, if the save button have never been pressed, is it possible to just hide it with CSS in that case?

**In code**

    if( save_button == pressed ) {
        var pressed = true;
    }

    if( pressed == true ) {
        hide_link = hide_with_css_url();
    } else {
        hide_link = reload_page_url();
    }

**Comment by distantnative** [comment]
Will try. Binding events to the save button is a little tricky as the panel already does a lot with it.
