### ISSUE TITLE
Iframe edit mode - Always have back bar on top

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#77]
When we are on frontend we need to hide or change the position of the panelbar, because of the elements we might have on the site.

When we are in editing mode, the full screen editor will always look the same. Therefor I see no reason to have the panelbar attached to the bottom, even if it's set to position bottom in the config. Now it's a part of the editor, not a part of the panelbar.

What do you think about always have it on top? I think it feels most natural. That might even kill a few bugs on the way.

**Comment by distantnative** [comment]
Will try this to get an idea about the feel. A little sceptic if it would jump around to much then.

**Comment by jenstornell** [comment]
I was also sceptic by the same reason until I tried it.

Why I think it works is that the editor bar feels so much like Kirby Panel and not like panelbar.
