### ISSUE TITLE
Keyboard shortcuts for show/hide and position

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#79]
I think it would be faster workflow if there was a way to show / hide the panel with keyboard shortcuts as well. Maybe even other stuff like:

- Show / hide panel
- Edit this page
- Panel

If it's a good idea, just be aware of different keys on Mac and PC.

**Comment by distantnative** [comment]
What would be good key combinations for these actions?

**Comment by distantnative** [comment]
At the moment:
alt + x: show/hide
alt + up/down: top/bottom
alt + E: edit
alt + P: panel

**Comment by distantnative** [comment]
Also not yet solved: What to do when in iframe view (right now you can still hide the panel bar)

**Comment by jenstornell** [comment]
For the iframe, just allow shortcuts that are in the back-bar? Like hide and hide + refresh?

alt + r = hide + refresh? when in back-bar edit mode?

I have not tried if the shortcuts work yet. On tuesday at 13 I will flood the issue-list again. :)

**Comment by jenstornell** [comment]
### Edit

alt + e is a good one. Too bad it will also open a menu in Google Chrome.
I also think it could be a toggle. Edit mode on / off (Return to page).

### Other ones

I like the other key combinations and I really love this function and how well it works. I hope it will work for Mac users as well.

**Comment by jenstornell** [comment]
### Position

I just figured out somthing about the position. As a complement to the combinations already added, this would be nice:

alt + arrow up - Position top (regardless of what is was before)
alt + arrow down - Position bottom (regardless of what is was before)

This way it would not toggle, just set. For me it would probably be more natural like that.

**Comment by jenstornell** [comment]
### Possible collision

I see a danger in the combinations, that the website maybe already have a set of shortcuts themselves. I think it's important to be able to turn it on / off in the config.php. I like default to be on and if there is a problem the user will notice and disable it at that point. Docs of that also important.

**Comment by distantnative** [comment]
### Current shortcuts
Shortcut  | Effect
------------ | -------------
`alt` + `x` | toggle visibility (show/hide)
`alt` + `-` | toggle position (top/bottom)
`alt`+ `up` | set position to top
`alt` + `down` | set position to bottom
`alt` + `E` | toggle edit mode
`alt` + `R` | close iFrame and Refresh
`alt` + `P` | go to panel

### Position
I tried this before, but wasn't really sure. Activated it again for you to see yourself. Problem is, that for me in Safari the page also starts scrolling a bit.

### Deactivate
In `config.php`:
```php
c::set('panelbar.keys', false);
```

**Comment by jenstornell** [comment]
### About alt + e

It's good to have e as in edit. Too bad Chrome uses it. Possible, not as good combinations for it:

- alt + c = c as in Change
- alt + 3 = E backwords
- alt + 0 = Some neutral number

I know, they are quite poor.

### Position

It works great in Chrome. How can position shortcut make it scoll in Safari and not shortcut for toggle position scoll? I think it's the best shortcut.

**Comment by distantnative** [comment]
Alt + U => update?

I think, I'll just leave the arrow shortcuts in. If it works for some browsers great, use it. If it doesn't work that well in Safari, just use alt + dash

**Comment by jenstornell** [comment]
alt + u, hmm. I think they are all equaly bad. Pick what you think is best.

About Safari. If it's possible to check if the browser is Safari in JS, you could block the feature for that browser. Just don't check webkit because Chrome uses webkit as well.

**Comment by jenstornell** [comment]
Any reason why it's alt + M? Or is it just a random letter? I'm ok with it, just curious.

**Comment by distantnative** [comment]
modify ;)

**Comment by jenstornell** [comment]
Edit, Change, Update, Modify. Seems to be quite a few to choose from. :)
