### ISSUE TITLE
panelbar::dropdown url false, still a link

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#8]
I really like the dropdown helper. It even works on the bottom.

1. In the example the url is set to false. Still it's a link around the text. Remove the link to be more correct.
2. I think it's a little strange to have the "first" array part. I think just having "label" or "title" for the first item would be more simple to understand. The question here is, it there a reason for the first item to ever be clickable? If yes, just look at my first point.

**Comment by jenstornell** [comment]
Now I saw that is also had to be named "first". Maybe it was the naming that was not clear to me. I don't have a suggestion of a better name but "first" to me sounds like a self made name. "title" or "label" as key might not be correct. I don't know.

"others" is also a name that sounds self made. Maybe call it "items" or something?

**Comment by distantnative** [comment]
Changed the naming:

```
panelbar::dropdown(array(
  'id'    => 'lang',
  'icon'  => 'flag',
  'label' => 'Language',
  'items' => array(
               0 => array(
                     'url' => …,
                     'text' => …
                    ),
               1 => array(
                     'url' => …,
                     'text' => …
                    ),
               …
             )
));
``

First item now never is a link, but just a label.

**Comment by jenstornell** [comment]
It looks great!
