### ISSUE TITLE
Dev - Panelbar bottom jumping

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#80]
When editing and then closing it makes a CSS jump which makes the panelbar bigger than before in height. On reload it's reset.

![image](https://cloud.githubusercontent.com/assets/927011/10246425/6a6c3592-6911-11e5-81de-a8a68932a7ac.png)

**Comment by distantnative** [comment]
It seems like this got fixed with the last changes on the develop branch.

**Comment by jenstornell** [comment]
Works for me!
