### ISSUE TITLE
Dev - Edit close does not reload data anymore, not even when saved

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#81]

**Comment by distantnative** [comment]
That was only temporary, new commit is on the dev branch.

**Comment by jenstornell** [comment]
Only work sometimes. I saved multiple times and it worked about 50% of the cases.

If it's really hard to get it working maybe a workaround would just be
```
< Return       Save and return
```

In the backbar.

**Comment by distantnative** [comment]
Hooking into submitting the form as an action is probably even more unreliable than just trying to listen to a submit. :/

**Comment by distantnative** [comment]
Maybe I have to set a higher timeout on the submit listener. Given that submits will occur a little later, cause they will involve changes that first have to be made.

**Comment by jenstornell** [comment]
I also tried to save and exit fast and it did not seem to keep up. What about this not so hackish solution? Too simple?

```
< Return       Return and refresh
```

**Comment by distantnative** [comment]
Yea, cause I have to set a timeout before binding a listener to the submit event, cause if the panel hasn't loaded yet, this will crash otherwise.

**Comment by jenstornell** [comment]
Hmm, are we talking about the same thing? The latest suggestion was this:

```
< Return       Return and refresh
```

**Return** = Hide / remove the iframe with JS. It does not care if the panel is loaded or if something was saved or not.

**Return and refresh** = An url back to the page. It does not care if the panel is loaded or if something was saved or not.

Then this would make rid of the JS iframe listening to events thing?
