### ISSUE TITLE
Revise docs for 0.6

### ISSUE THREAD

**Issue by distantnative** [distantnative/panel-bar#83]
- [x] Renamed `helpers::` to `build::`
- [x] Removed callable elements for security reasons (just call the function and pass a string or - even better - use new CSS/JS/HTML hooks
- [x] Removed old way of passing custom CSS/JS (pseudo-hooks)
- [x] New methods to register custom CSS/JS
```php
echo panelbar::show(array('elements' => $items, 'css' => '.mylove{}'));
```
```php
echo panelbar::show(array('css' => false));
echo panelbar::css('.mylove{}');
```
- [x] Callable element functions get output and assets parameters to register hooks:
```php
$items = array(
    'panel',
    'add',
    'edit',
    'help' => 'customfunction',
    'loadtime',
    'user',
    'logout'
);

function customfunction($output, $assets) {
  $assets->setHook('js', '…');
  $assets->setHook('js', '…');
  …
  $output->setHook('element', …)
}

echo panelbar::show(array('elements' => $items));
```
- [x] Instead of returning just the element string, providing an array as element is also a way to pass on custom JS/CSS
- [x] ID on element helpers
- [x] Keyboard Shortcuts  

Shortcut  | Effect
------------ | -------------
`alt` + `x` | toggle visibility (show/hide)
`alt` + `-` | toggle position (top/bottom)
`alt`+ `up` | set position to top
`alt` + `down` | set position to bottom
`alt` + `E` | toggle edit mode
`alt` + `R` | close iFrame and Refresh
`alt` + `P` | go to panel

- [x] Changelog -> #98
- [ ] Info for getkirby-themes.com
- [ ] More and updated Screenshots

**Comment by jenstornell** [comment]
Just to make this clear. How does this look with the new syntax?

```php
$items = array(
	'panel',
	'add',
	'edit',
	panelbar::link(array(
		'id'     => 'panel',
		'icon'   => 'rotate-right',
		'url'    => site()->url() . '/update-kreditgivare/?update=true',
		'label'  => 'Sync',
		'mobile' => 'icon',
	)),
	panelbar::box(array(
		'id'     => 'panel2',
		'icon'   => 'clock-o',
		'label'  => 'Testing box2',
		'content' => '<div class="test" style="background: red;">icon</div>',
	)),
	'loadtime',
	'images',
	'logout'
);

echo panelbar::show( array( 'elements' => $items ) );
```
