### ISSUE TITLE
Update version of FontAwesome

### ISSUE THREAD

**Issue by distantnative** [distantnative/panel-bar#85]
Load it from plugin folder instead from panel then.

**Comment by jenstornell** [comment]
http://localhost/kirby/panelssets%0Fonts%0Fontawesome-webfont.woff?v=4.2.0 Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by distantnative** [comment]
That's weird - could you look into the `style`-block what the path is in your setup?
Should be:
```css
@font-face{font-family:'FontAwesome';src:url("../../../../panel/assets/fonts/fontawesome-webfont.woff?v=4.2.0") format("woff");
``

**Comment by jenstornell** [comment]
Style-block says:

```
@font-face{font-family:'Source Sans Pro';font-style:normal;font-weight:400;src:url(panel\assets\fonts\sourcesanspro-400.woff) format("woff")}
```

**Comment by distantnative** [comment]
Realized that I can't really get this from a plugin subfolder, because the htaccess will always block the browser to get the font file. So gonna stick with the one from the panel, cause I'd hate a CDN request even more.

**Comment by jenstornell** [comment]
That's fine for me and it works with my setup now.
