### ISSUE TITLE
Fileviewer design: improvements

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#93]
Maybe this is still ugly but I think I have some ideas that might work.

- Background as a transparancy pattern (like Photoshop)
- Border to show the ends
- Label not so gradient

![image](https://cloud.githubusercontent.com/assets/927011/10302381/26c18e70-6c0c-11e5-9359-4f06f16f8215.png)

**Comment by jenstornell** [comment]
...and with labels not overlaping images. I know it's a little buggy, too much space on top.

![image](https://cloud.githubusercontent.com/assets/927011/10302468/f6a7cfd2-6c0c-11e5-91bb-3899b394a48e.png)

**Comment by distantnative** [comment]
Pattern too small?
<img width="509" alt="screen shot 2015-10-10 at 14 44 06" src="https://cloud.githubusercontent.com/assets/3788865/10411185/6636ed76-6f5d-11e5-91df-26d024ee9aa5.png">

**Comment by distantnative** [comment]
Transparent pattern already added. More to follow in v0.8

**Comment by distantnative** [comment]
<img width="745" alt="screen shot 2015-10-11 at 19 28 28" src="https://cloud.githubusercontent.com/assets/3788865/10417968/59aceab4-704e-11e5-8421-199971d77a75.png">
