### ISSUE TITLE
Pixel-bug on back-bar

### ISSUE THREAD

**Issue by jenstornell** [distantnative/panel-bar#95]
I know this is a tiny thing but look to the right on the slider. It differs 2 pixels.

![image](https://cloud.githubusercontent.com/assets/927011/10305575/2f45b85e-6c21-11e5-9819-fcbc677d7d74.png)

When setting back-bar margin-top to 0px it's showing this. A 2px top border on the panel and that is probably why it appears.

![image](https://cloud.githubusercontent.com/assets/927011/10305602/58818ba8-6c21-11e5-8396-499ac7b049f1.png)

**Comment by distantnative** [comment]
Can't follow this, nor reproduce atm:

Where does this 2 pixel difference occur? What do you mean by `back-bar`, which exact element needs to be set to `margin-top: 0` to see this?

**Comment by jenstornell** [comment]
Look at the top of the first part of this image. I call this the "backbar" because it takes you back to the frontend. To the right of the first backbar there is a two pixel jump.

Compare it to the second part of the image when I scolled down a bit. There is no jump.

When changing .panelbar-iframe__iframe { top: 48px } to 0px; there is a 2px top line. I think that is why it appears.

![image](https://cloud.githubusercontent.com/assets/927011/10447553/a9a56914-7185-11e5-9f35-a15a17c31215.png)

**Comment by distantnative** [comment]
Sorry, but I can't reproduce this. Changing it to `top: 0pc` also doesn't reveal it. That is Chrome on Windows?

**Comment by jenstornell** [comment]
I tried a fresh install of Kirby and it does not add the pixel problem. Weird but it's not a panelbar problem then. Sorry about that. It's probably some of my js plugins or something.
